### ISSUE TITLE
Kehitysympäristön pystytys

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-lahti#10]
- [x] kehitysympäristö Lahden toteutusta varten kehittäjien koneelle
- [x] pushataan muutokset GitHubiin
- [x] testataan
- [x] kun kehitysympäristössä asiat kunnossa, toteutus Lahden palvelimelle

**Comment by SannaJokela** [comment]
Pitää tehdä migraatioskriptien fiksauksia ja automatisointia.

**Comment by SannaJokela** [comment]
Done
