### ISSUE TITLE
Wheel antaa virheilmoituksia DVV-aineiston päivitysajossa

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#100]
Ajo menee läpi ja kohteet päivittyvät, mutta ainakin asoy-kohteissa on kummallisuuksia.

Kuvassa näkyy asoy-kohteita, jotka ovat muodostuneet oikein ja säilyneet virheettöminä päivityksen läpi, mutta myös kummallisuuksia, joissa päivitys on mennyt pieleen: rakennksista on syntynyt useita kohteita ja päivämääräasetukset ovat vinossa. Tutkittava johtuuko wheelillä ajetun päivityksen ajonaikaisista virheistä vai jostain muusta.

![Image](https://github.com/GispoCoding/jkr-lahti/assets/83061576/891eef41-a04b-49b3-a934-5a19fbd35c65)

**Comment by ismogis** [comment]
Ensimmäisen kuvakaappauksen virheilmoista suurin osa johtuu siitä, että salasana ei mene perille. Lisäksi siellä on joku outo tietokannan luonti, mitä ei kaiketi pitäisi tulla.

**Comment by Mtk112** [comment]
Testattu Lahdessa ja todettu toimivaksi.
