### ISSUE TITLE
Tee tietomalliin viranomaispäätösten vaatimat muutokset

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#108]
Päätöstietojen Excelistä tallennetaan seuraavat kentät:

- Numero
-- muutetaan "asiatunnus" muotoon "paatosnumero"

- Lähettäjä/vastaanottaja
-- lisätään uusi kenttä (text)

- Päätös 1
-- tapahtumalaji_koodi ja paatostulos_koodi, lisätään koodistoihin

- Voimassa alkaen
-- tarkistettava, mikä pvm mallissa vastaa tätä

- Voimassa asti
-- tarkistettava, mikä pvm mallissa vastaa tätä

- Lisätiedot 1
-- lisätään uusi kenttä (text)
-- pohdittava, siirretäänkö tieto tyhjennysvälistä ja velvoitepoikkeamista muihin tauluihin

Kohdennus tapahtuu seuraavien kenttien perusteella:

- PRT 1
- Lähiosoite
- Postinumero
- Postitoimipaikka

Seuraavat kentät nykyisessä tietomallissa lienevät tarpeettomia:

- paatospykala
- tilanne
- hakusanat

Lisäksi pohdittava, miten rakennus liitetään päätökseen. Tarvitaanko rakennuksen PRT:lle oma kenttä vai vaihdetaanko kohde-päätös-relaatio rakennus-päätös-relaatioksi? Velvoite kohdistuu aina kohteeseen, mutta kohteen saa toki haettua rakennuksen kautta.

**Comment by ismogis** [comment]
- Tauluun jkr.viranomaispaatokset tarvitaan seuraavat muutokset:

1. asiatunnus -> paatosnumero
2. uusi kenttä vastaanottaja (text)
3. poistetaan vanhat pvm-kentät
4. lisätään kentät alkupvm ja loppupvm
5. poistetaan kentät paatospykala, tilanne ja hakusanat
6. uusi kenttä akppoistosyy (koodisto)
7. uusi kenttä tyhjennysvali (smallint)
8. uusi kenttä jatetyyppi_id

- Lisätään tapahtumalajit tauluun jkr_koodistot.tapahtumalaji.

- Lisätään päätöstulokset tauluun jkr_koodistot.paatostulos.

- Vaihdetaan kohde-päätös-relaatio rakennus-päätös-relaatioksi.

**Comment by ismogis** [comment]
Muista päivittää myös kuva tietomallista (ei pelkästään dbm-tiedosto).
