### ISSUE TITLE
Päätöstietojen import

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-lahti#11]
Tuodaan yksi tiedosto kerrallaan.

**Comment by ltalve** [comment]
Päätöstaulun muokkaaminen datan mukaiseksi

**Comment by ltalve** [comment]
Muistiin: päätöksiä saatetaan joskus tehdä myös liittyen kompostointi-ilmoituksiin, mutta suhteellisen harvinaista. Pitää miettiä miten nämä käsitellään.

**Comment by ltalve** [comment]
- Tuotos; päätöstiedot viety tietokantaan (vietävä ajanjakso sovitaan erikseen)
- Päätöstiedot viedään viranomaispäätökset tauluun
- Taulujen kenttien nimikkeiden arvojen määrittely
- Määriteltävä millä nimellä viedään viranomaispäätökset. Lähtö aineisto päätökset mastertiedostossa:
- - Kompostointi kielteinen
- - Tyhjennysväli kielteinen
- - Tyhjennysväli myönteinen
- - Perusmaksu kielteinen
- - Perusmaksu myönteinen
- - AKP kielteinen
- - AKP myönteinen
- - Keskeyttäminen kielteinen
- - Keskeyttäminen myönteinen
- - Kimppa kielteinen

**Comment by ismogis** [comment]
Tyhjennysväli kannattaa käsitellä toteutuksessa vasta päätöstuloksen ja tapahtumalajin jälkeen.
