### ISSUE TITLE
Aseta kaikki kohteelle tehdyt päätökset ja ilmoitukset näkyviin käyttöliittymässä

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#114]
Käyttöliittymässä tulee olla näkyvissä kaikki kohteelle tehdyt päätökset ja siihen liittyvät ilmoitukset, ts. myös ne, jotka ovat jo rauenneet.

**Comment by ismogis** [comment]
Viranomaispäätökset on mukana projektissa jo nyt, kompostointi-ilmoitukset on lisättävä. Päätöksille tehdään kuitenkin näkymä kantaan, josta ne saadaan näkymään helposti kohteen yhteydessä. Kompostointi-ilmoituksille ei tarvita samanlaista näkymää, sillä data voidaan lukea kompostorin_kohteet-taulusta.
