### ISSUE TITLE
DVV-aineiston synkronointi

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-lahti#12]
Luetaan DVV-aineistosta
- [x] Rakennukset
  - [x] Tiedot

**Comment by LKajan** [comment]
Saadaanko huoneistömäärää jostakin?

**Comment by AnniinaMet** [comment]
> Saadaanko huoneistömäärää jostakin?

Meillä on olemassa erillisessä tiedostossa huoneistomäärät, mutta tieto ei ole enää ihan tuoretta. Käymme sisäistä keskustelua voiko kyseistä aineistoa vielä käyttää. DVV:llä on menossa Jätehuollon poimintapaketin uudelleen määritys ja on mahdollista että uudessa versiossa myös huoneistomäärä on mukana, mutta toistaiseksi uuden määrittelyn mukaisesta sisällöstä ei vielä ole tietoa.

**Comment by AnniinaMet** [comment]
Huoneistomäärälle tulee siis olla paikka, kuten myös asukasmäärälle

**Comment by LKajan** [comment]
Huoneistomäärälle on jo tietomallissa paikka. Asukasmäärälle tehty issue https://github.com/GispoCoding/jkr-core/issues/10
