### ISSUE TITLE
Lue eri tyhjennysrytmeillä tuleva sama kuljetustieto kantaan

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#123]
Kuljetustietojen tyhjennysvälit: jos samalla asiakkuudella eri tyhjennysrytmejä (esim. harvemmin talvella ja keväällä/kesällä useammin), kuljetustietoaineistossa kaksi tulee samalla rivillä (tyhjennysväli 1 ja 2), mutta mahdollinen (harvinainen) kolmas rytmi tulee omalla rivillään. Molemmat rivit tulee lukea kantaan.

Kaksi eri rytmiä samalla kvartaalilla menevät sarakkeisiin tyhj.väli1 ja tyhj.väli2. Toisen rytmin voimassaoloajat luetaan sarakkeista voimassaoloviikotalkaen2/voimassaoloviikotasti2. Voimassaolosarakkeissa on viikkonumerot.

Tehdään #121 jälkeen.

**Comment by ismogis** [comment]
Luodaan oma luokka AsiakasRow, johon luetaan kuljetusdata riveittään. Yhdistetään AsiakasRowt Asiakas-olioiksi, jossa ne kentät, joiden arvot vaihtelevat riveittäin, ovat listoina. Tehdään listoille tarvittavat operaatiot vain kerran ennen kuin data viedään kantaan. Tällä tavalla prosessin ei pitäisi hidastua oleellisesti.
