### ISSUE TITLE
Päivitä tietomallin png-versio

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#129]
Tietomallin png-kuva db-kansiossa ei ole ajan tasalla. Päivitetään esim. siinä vaiheessa, kun kuljetustietojen korjaukset on saatu kuntoon. Dbm-muotoista kuvausta on pidetty yllä jatkuvasti.

**Comment by ltalve** [comment]
Päivitetty kuva: https://github.com/GispoCoding/jkr-lahti/blob/main/docs/Lahti_jkr_db_model_7_2_2024.png

Tiedoksi @AnniinaMet @TiiaY
