### ISSUE TITLE
Urakoitsijoiden asiakkaiden kohdennus JKR-kohteisiin

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-lahti#13]

**Comment by ltalve** [comment]
Vuosien 2018-2021 asiakasaineisto, tuodaan kerran

**Comment by Rikuoja** [comment]
Tässä tekemättä:

- Mitä kohdentumattomille kuljetuksille tehdään? Nyt ne jäävät kohdentumatta, kunnes ulkoinen asiakasnumero on lisätty kohteelle käsin.
- Muutetaanko kohdennuslogiikkaa niin, että nimellä ei kohdisteta? Tällä hetkellä nimellä kohdistetaan, jos asiakasnumeroa ei löydy ja osoitteessa useampi kohde.

**Comment by Rikuoja** [comment]
Tämä on ristiriidassa issuen https://github.com/GispoCoding/jkr-lahti/issues/13 kanssa, jos kohdentumattomia kuljetuksia ei tuoda *ollenkaan*.

Riittääkö käyttäjätarinaan https://github.com/GispoCoding/jkr-lahti/issues/40 se, että alkuperäiset excelit ovat tallessa, mutta kohdentumattomia kuljetukset excelistä ei ole tallennettu tietokantaan?

**Comment by Rikuoja** [comment]
Tämänhetkinen logiikka: <img width="899" alt="image" src="https://user-images.githubusercontent.com/9367712/213165179-7b8a90a0-03de-4264-9ac6-374475235b6a.png">

**Comment by Rikuoja** [comment]
Historiatietojen osalta mietittävä miten pitkälle taaksepäin on realistista sanoa, että kuljetustieto todella osuu kohteelle, joka luotu “nykytiedon” pohjalta. Sama kysymys kuin issuessa https://github.com/GispoCoding/jkr-core/issues/25 eli onko nyt päätetty, että 2021 aiempaa dataa ei viedä kuljetuksista? Tällainen ajatus esitettiin käyttäjätarinoiden yhteydessä.

**Comment by TiiaY** [comment]
**Kuljetustiedon kohdennus:** 

  

1. PRT (löytyykö pelkällä PRT:llä vastaavaa kohdetta (ei muuta tarkistusta)) 

3. urakoitsija on sama, kohdeosoite on sama ja haltijan nimi sama. (Urakoitsijan ID täytyy olla sama, urakoitsijan aineiston osoitteen pitää olla sama ja kohteen osoite ei saa olla tyhjä, haltijan nimi pitää olla sama mitä kohteella, kohteen täytyy olla kohdistunut (kiinteistötunnus kenttä ei saa olla tyhjä)) 

5. urakoitsija on sama, kohdeosoite on sama ja kohde-Id on sama (Urakoitsijan ID on sama ja urakoitsijan kohde-id ja osoite on sama ja kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))

**Comment by TiiaY** [comment]
Jos kohteella samalle aikavälille useampia saman urakoitsijan kuljetuksia (esim. eri asiakasnumero, eri osoite jne.), nämä on tuotava kaikki. Tällä hetkellä seuraava kuljetusrivi ylikirjoittaa edellisen, eikä erillistä kuljetusta tuoda.

 Jos samalle kohteella on useampia kuljetuksia, joita halutaan katsella rakennuksittain, kohteet jaettava pienempiin osiin TAI lisättävä jokaiselle kuljetustiedolle joku tarkempi rakennus-/osoitetieto: https://github.com/GispoCoding/jkr-lahti/issues/68

**Ei ole tarpeen katsella rakennuksittain. Jokaisella kuljetustiedolla tulee olla olla oma osoiterivi. Kuljetusyrityksen ilmoittamat tiedot ml osoitetiedot tulee tallentaa.**

 Mitä kohdentumattomille kuljetuksille tehdään? Nyt ne jäävät tuomatta, kunnes ulkoinen asiakasnumero on lisätty kohteelle käsin.
 Asiakasnumerot voi lisätä käsin (https://github.com/GispoCoding/jkr-lahti/issues/59) ja ajaa kohdennuskomennon uudestaan. Testataan, että tämä prosessi toimii.
TAI
 Jos rivillä on ulkoinen asiakasnumero tai vastaava tunniste, tuodaan se tietokantaan vaikka kohdennus ei onnistuisi. Tällöin asiakastietorivin voi lisätä qgisissä käsin kohteelle, kunhan https://github.com/GispoCoding/jkr-lahti/issues/59

**16.1. oli puhe PRT:n etsimisestä eli jätehuolto etsii PRT:n ei asiakasnumeroa. Miten tuodaan paritalot ensimmäisellä kerralla, onko mahdollista täydentää jkr-kohdeid käsin?**

 Muutetaanko kohdennuslogiikkaa niin, että nimellä ei kohdisteta? Tällä hetkellä nimellä kohdistetaan, jos asiakasnumeroa ei löydy ja osoitteessa useampi kohde. Tällaisia kohteita ovat etenkin paritalot, mutta myös muita tapauksia monistuneista kohteista varmasti löytyy.

**•	Jätehuolto toimittanut 19.12.2022 kohdennusehdot:
1.	PRT (löytyykö pelkällä PRT:llä vastaavaa kohdetta (ei muuta tarkistusta)) 
2.	urakoitsija on sama, kohdeosoite on sama ja haltijan nimi sama. (Urakoitsijan ID täytyy olla sama, urakoitsijan aineiston osoitteen pitää olla sama ja kohteen osoite ei saa olla tyhjä, haltijan nimi pitää olla sama mitä kohteella, kohteen täytyy olla kohdistunut (kiinteistötunnus kenttä ei saa olla tyhjä)) 
3.	urakoitsija on sama, kohdeosoite on sama ja kohde-Id on sama (Urakoitsijan ID on sama ja urakoitsijan kohde-id ja osoite on sama ja kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))** 


 Tuontia käsiteltäessä päätettiin, että vain dvv-kohteisiin kohdennetaan, ja loppuaineistosta jää lista kuljetuksista, joita ei ole kohdennettu eikä tallennettu tietokantaan.
 Riittääkö käyttäjätarinaan https://github.com/GispoCoding/jkr-lahti/issues/40 se, että alkuperäiset kuljetusexcelit ovat tallessa, mutta kohdentumattomia kuljetuksia excelistä ei ole tallennettu tietokantaan?
**	Riittää, kohdentumattomista pitää saada raportti ulos.**

 Jos halutaan myös kohdentumattomat ei-duplikoidut rivit tietokantaan, ne voidaan tuoda kohdentumattomina asiakastietoina sen jälkeen kun tietomallimuutos https://github.com/GispoCoding/jkr-lahti/issues/59 on tehty
 Historiatietojen osalta mietittävä miten pitkälle taaksepäin on realistista sanoa, että kuljetustieto todella osuu kohteelle, joka luotu “nykytiedon” pohjalta. Sama kysymys kuin issuessa https://github.com/GispoCoding/jkr-core/issues/25 eli onko nyt päätetty, että 2021 aiempaa dataa ei viedä kuljetuksista? Tällainen ajatus esitettiin käyttäjätarinoiden yhteydessä.
TAI

 Tehdään jokaisesta asiakkaasta oma kohde, koska jokaisen rakennuksen kuljetuksia/sopimuksia halutaan tarkastella erikseen, aivan kuten Tampereella. Tällöin koko DVV-kohteidenluontilogiikka on turha.

**V1 viedään 2021 eteenpäin

V2 Kohteiden luonti kuljetustietojen pohjalta ei ole vaihtoehto koska,
•	Kuljetusyritys ei tiedä minkä rakennusten jätteet ovat kuljetusrivitiedossa. -> Suuri osa rakennuksista jää ilman kuljetuksia, koska ne kohdentuvat vain yhdelle rakennukselle. 
•	Liittymättömiä ei voi tarkastella kohteittain, koska liittymättömistä ei muodostu kohteita. -> Liittymisen seurantaa ei voi tehdä.**

**Comment by Rikuoja** [comment]
**16.1. oli puhe PRT:n etsimisestä eli jätehuolto etsii PRT:n ei asiakasnumeroa. Miten tuodaan paritalot ensimmäisellä kerralla, onko mahdollista täydentää jkr-kohdeid käsin?**

Tällä hetkellä paritalot tosiaan kohdennetaan urakoitsijalla, prt:llä/osoitteella *ja* asiakkaan nimellä, koska kahdella paritalokohteella on sama osoite ja sama prt. Eli jos asiakkaan nimessä on virheitä, paritalo ei koskaan kohdennu.

Kohde_id on tosiaan mahdollista täydentää paritalon oikealle puoliskolle ulkoiseen asiakastietoon. Tämän jälkeen uudelleen tuomalla tämä paritalon puolisko kohdentuu oikein, vaikka asiakkaan nimessä olisi joku ongelma.

**Comment by Rikuoja** [comment]
**• Jätehuolto toimittanut 19.12.2022 kohdennusehdot:

1. PRT (löytyykö pelkällä PRT:llä vastaavaa kohdetta (ei muuta tarkistusta))
2. urakoitsija on sama, kohdeosoite on sama ja haltijan nimi sama. (Urakoitsijan ID täytyy olla sama, urakoitsijan aineiston osoitteen pitää olla sama ja kohteen osoite ei saa olla tyhjä, haltijan nimi pitää olla sama mitä kohteella, kohteen täytyy olla kohdistunut (kiinteistötunnus kenttä ei saa olla tyhjä))
3. urakoitsija on sama, kohdeosoite on sama ja kohde-Id on sama (Urakoitsijan ID on sama ja urakoitsijan kohde-id ja osoite on sama ja kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))**

Tässä tosiaan onkin isompi ero aiempaan toteutukseen.

Ymmärsin että 2021-tiedot tuotiin alunperin juuri siksi, että tämän jälkeen urakoitsijan kohde-id:illä voitaisiin kohdistaa oikein seuraavan vuoden tiedot (kun osoitteissa, nimissä ja sellaisissa voi olla kirjoitusvirheitä). Kohde-id:tä on nyt käytetty kaikkien kuljetusten kohdistamiseen ihan ensisijaisena tietona, jos urakoitsijan kohde-id löytyy jo meiltä joltain kohteelta.

Uusilla ehdoilla kohdennus vaatisi aina oikein kirjoitetun osoitteen. Vasta jos osoite löytyy mutta asiakkaan nimi ei jostain syystä ole sama, katsottaisiin viimeiseksi kohde-id:tä.

Muutos onnistuu toki, mutta silloin väärinkirjoitetut osoitteet jäisivät kokonaan kohdentumatta, vaikka urakoitsijan kohde-id löytyisi. Urakoitsijan kohde-id:tä ei siis hyödynnettäisi juuri koskaan, ainoastaan varmistamaan kohde siinä tilanteessa, että samassa osoitteessa on kohde jonka asiakkaan nimi on kirjoitettu eri tavalla.

Onko tämä tarkoitus? En osaa suoraan sanoa, kuinka paljon nykyisessä datassa on kuljetuksia, jotka on kohdentuneet juuri kohde-id:n avulla (esim. kuljetusosoitteessa virhe), mutta ne jäisivät sitten kohdentumatta. Eli miksi ei haluta tuoda kuljetuksia, joiden oikea kohde tiedetään, mutta kuljetusosoitteessa on kirjoitusvirhe; onko syytä olettaa että kohde on sittenkin väärä vaikka se on urakoitsijalla samalla kohde-id:llä kuin edellisenä vuonna?

![Image](https://user-images.githubusercontent.com/9367712/218117197-69bfcca1-43a4-46dd-912d-f7718ada2d0f.png)

**Comment by Rikuoja** [comment]
3. kysymys: Mitä tarkoittaa **kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))**, en ymmärrä? Siis sitä, että kohteeseen pitää kuulua jokin rakennus, jolla on PRT, tai jokin rakennus, jolla on kiinteistötunnus? Vai tarkoittaako tämä samaa kuin 2. kysymyksen lause?

**Comment by TiiaY** [comment]
> **• Jätehuolto toimittanut 19.12.2022 kohdennusehdot:
> 
> 1. PRT (löytyykö pelkällä PRT:llä vastaavaa kohdetta (ei muuta tarkistusta))
> 2. urakoitsija on sama, kohdeosoite on sama ja haltijan nimi sama. (Urakoitsijan ID täytyy olla sama, urakoitsijan aineiston osoitteen pitää olla sama ja kohteen osoite ei saa olla tyhjä, haltijan nimi pitää olla sama mitä kohteella, kohteen täytyy olla kohdistunut (kiinteistötunnus kenttä ei saa olla tyhjä))
> 3. urakoitsija on sama, kohdeosoite on sama ja kohde-Id on sama (Urakoitsijan ID on sama ja urakoitsijan kohde-id ja osoite on sama ja kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))**
> 
> Tässä tosiaan onkin isompi ero aiempaan toteutukseen.
> 
> Ymmärsin että 2021-tiedot tuotiin alunperin juuri siksi, että tämän jälkeen urakoitsijan kohde-id:illä voitaisiin kohdistaa oikein seuraavan vuoden tiedot (kun osoitteissa, nimissä ja sellaisissa voi olla kirjoitusvirheitä). Kohde-id:tä on nyt käytetty kaikkien kuljetusten kohdistamiseen ihan ensisijaisena tietona, jos urakoitsijan kohde-id löytyy jo meiltä joltain kohteelta.
> 
> Uusilla ehdoilla kohdennus vaatisi aina oikein kirjoitetun osoitteen. Vasta jos osoite löytyy mutta asiakkaan nimi ei jostain syystä ole sama, katsottaisiin viimeiseksi kohde-id:tä.
> 
> Muutos onnistuu toki, mutta silloin väärinkirjoitetut osoitteet jäisivät kokonaan kohdentumatta, vaikka urakoitsijan kohde-id löytyisi. Urakoitsijan kohde-id:tä ei siis hyödynnettäisi juuri koskaan, ainoastaan varmistamaan kohde siinä tilanteessa, että samassa osoitteessa on kohde jonka asiakkaan nimi on kirjoitettu eri tavalla.
> 
> Onko tämä tarkoitus? En osaa suoraan sanoa, kuinka paljon nykyisessä datassa on kuljetuksia, jotka on kohdentuneet juuri kohde-id:n avulla (esim. kuljetusosoitteessa virhe), mutta ne jäisivät sitten kohdentumatta. Eli miksi ei haluta tuoda kuljetuksia, joiden oikea kohde tiedetään, mutta kuljetusosoitteessa on kirjoitusvirhe; onko syytä olettaa että kohde on sittenkin väärä vaikka se on urakoitsijalla samalla kohde-id:llä kuin edellisenä vuonna?

**Selvennys**
Tässä on tarkoitettu, että kohdennussäännöt vertaavat edellisiin kohdennuksiin **EI vrk tietoon**. Eli kuljetusid on sama kuin edellisessä kuljetustiedossa, osoite on sama kuin edellisessä kuljetustiedossa. 

Ensimmäisessä kohdennuksessa oli PRT eli sen perusteella kuljetukset meni kertaalleen kohdilleen.

**Comment by TiiaY** [comment]
> 2. kysymys: Mitä tarkoittaa **kohteen täytyy olla kohdistunut (kiinteistötunnus kenttä ei saa olla tyhjä))**, en ymmärrä?
> 
> Kaikilla rakennuksilla on kiinteistötunnus sekä erikseen PRT. Tarkoittaako tämä, että kuljetustiedoissa pitää olla kiinteistötunnus-kentässä (jonka nimi on hämäävä) täytetty PRT? Miten tämä silloin eroaa ehdosta 1, jossa meillä on jo PRT? Miksei sillä kohdenneta suoraan? Vai missä pitää olla ei-tyhjä kiinteistötunnuskenttä?
> 
> Kaikilla kohteillahan on aina rakennuksia, ja rakennuksilla on aina PRT. Ei meillä ole kohteita, joissa ei olisi kiinteistöä tai rakennusta. Vai pitääkö tarkistaa että kohteen jollakin rakennuksella on kiinteistötunnustieto dvv:ssä? Vai jotain muuta?

Ei tarkoita tässä mitään, liittyy edelliseen järjestelmään.

**Comment by TiiaY** [comment]
> 3. kysymys: Mitä tarkoittaa **kohteelta pitää löytyä kiinteistötunnus (aineistossa ei tarvitse olla kiinteistötunnusta))**, en ymmärrä?
> 
> Siis sitä, että kohteeseen pitää kuulua jokin rakennus, jolla on PRT, tai jokin rakennus, jolla on kiinteistötunnus? Vai tarkoittaako tämä samaa kuin 2. kysymyksen lause, eli että kuljetusaineistosta pitää löytyä jotain?

Liittyy myös nykyiseen järjestelmään.

**Comment by Rikuoja** [comment]
> Selvennys
> Tässä on tarkoitettu, että kohdennussäännöt vertaavat edellisiin kohdennuksiin EI vrk tietoon. Eli kuljetusid on sama kuin edellisessä kuljetustiedossa, osoite on sama kuin edellisessä kuljetustiedossa.
>
> Ensimmäisessä kohdennuksessa oli PRT eli sen perusteella kuljetukset meni kertaalleen kohdilleen.

Edellisen kuljetustiedon osoitehan on voinut olla mitä tahansa, koska kohdennus on tehty PRT:n avulla. Osoiteta ei tarkisteta ollenkaan ensimmäisellä kerralla, koska PRT on tiedossa.

Jos seuraavassa kohdennuksessa kuljetus-id on sama, miksi osoitteella on väliä? Tässä voi tosiaan käydä niin, että jos seuraavissa kuljetuksissa osoite on kirjoitettu jotenkin väärin, niin kuljetus jää kohdentumatta, vaikka kohde olisi tiedossa kuljetus-id:n perusteella.

Mikä on siis se käyttötapaus, jossa kuljetus-id on sama, mutta osoite on kirjoitettu eri tavalla kuin viime kerralla, ja silloin ei halutakaan tuoda kuljetusta kohteelle? Onko tämä yleistä, ja mitä kohdentumattomalle kuljetukselle silloin tehdään?

**Comment by Rikuoja** [comment]
Eli jos nyt olen oikein ymmärtänyt kohdennusehdot (poistin aikaisempaan järjestelmään liittyvät lauseet):

1. PRT (löytyykö pelkällä PRT:llä vastaavaa kohdetta (ei muuta tarkistusta))
**2.** urakoitsija on sama, kohdeosoite on sama ja **haltijan nimi sama**. (Urakoitsijan ID täytyy olla sama, urakoitsijan aineiston osoitteen pitää olla sama ja kohteen osoite ei saa olla tyhjä, haltijan nimi pitää olla sama mitä kohteella)
**3.** urakoitsija on sama, **kohdeosoite on sama** ja kohde-Id on sama (Urakoitsijan ID on sama ja urakoitsijan kohde-id ja osoite on sama)

Eli tässä on kolme eroa (lihavoituina) nykyiseen toteutukseemme. Ensinnäkin halutaan, että osoitteen kirjoitusasu ei muutu, vaikka kohde-id olisikin sama, kuten yllä totesin. Toiseksi halutaan, että osoitteen lisäksi tarkistetaan myös haltijan nimen kirjoitusasu, jos kohdennetaan pelkällä osoitteella, ja jos nimi eroaa, ei kohdenneta.

Viimeinen ero nykytoteutukseen on kohtien 2 ja 3 järjestys. Miksi kohdennus halutaan tehdä ensisijaisesti osoitteella/nimellä ja vasta sitten kohde-id:llä? Eikö tunnettu kohde-id ole varmempi kohdennustapa epäselvissä tilanteissa?

Myös ei-kohdentuneiden kohdennus oli ajateltu tehdä niin, että qgisissä haluttuun kohteeseen lisätään kohdentumaton urakoitsijan kohde-id, ja sen jälkeen rivi kohdennetaan aina tähän kohteeseen. Jos kohdennus tehdäänkin nimellä ja osoitteella ennen kohde-id:tä, on periaatteessa mahdollista, että lisätyllä kohde-id:llä ei tulevaisuudessa kohdennetakaan, jos vaikkapa uudesta dvv-aineistosta löytyykin toinen kohde, jolla on tämä osoite ja asukas (esim. paritalon toiseen puolikkaaseen muuttaa sopivasti sama sukunimi). Oletin, että kohde-id olisi näissä tapauksissa varmempi, eli **3.** olisi parempi olla ennen **2.**:ta.

**Comment by ltalve** [comment]
@TiiaY Tästä oli ilmeisesti teillä suunnitteilla joku uusi logiikka? Se on hyvä päivittää tänne, mutta voidaan käydä sitä ensin suullisesti läpi. Eli tällä hetkellä ei kysymyksiä tässä, poistan tägin.

**Comment by TiiaY** [comment]
Kommentoimme tuonne: Kuljetustietoexcelien importin toteutus #3

**Aineistot**

•	Jätehuolto päivittää kuljetustietoaineistot, ei viedä vanhoja.

•	Gispon tuottaa ennen aineistojen toimisamista dokumentin/merkitsee kuljetustieto-Exceliin, mitkä tiedot ovat pakollisia ja mitkä tiedot viedään JKR:ään. 
o	UrkId ei tulisi olla pakollinen. 

•	Vietävän aineiston dokumentointi: Tehtävä sisäinen ohje miten kuljetustietoja JKR:ään muokataan mikäli se poikkeaa RAKE-muokkauksesta.
 
**Kohdistus**
 
**Kohdistus 2021**
1.	prt:n perusteella

**Kohdistus 2022 ja eteenpäin**
1.	PRT
3.	Urakoitsija ID ja asiakasnumero
4.	Urakoitsija ID ja sama osoite kuin edellisen jakson kuljetustiedoissa.
 
**Muuta**
•	Jätelajit piktogrammijärjestelmän mukaisesti.
•	Aluekeräyspisteet viedään sekajätteenä. Sopimustyyppikohtaan aluekeräyspiste. Keskusteltava vielä Gispon kanssa.
•	Sysmän kohteet, vrk-tiedot ja kuljetustiedot poistettava.
 
**Vastauksia Gispon huoliin**
 
•	 Aina kohdetta ei löydy. (Tampereella tämä korjataan luomalla uusi kohde. Tällöin se voi osua päällekkäin jonkun olemassaolevan kohteen kanssa, mutta omistaja tai muut tiedot ovat eri. Meillä ei toistaiseksi luoda uutta kohdetta kuljetustiedoista.) Pitää voida luoda käsin kohde ja kohdentaa käsin.

•	2021: Osa aineiston riveistä monistuneita, sama tieto tuotu vain kertaalleen (jos tietokannassa on jo saman aikavälin saman jätelajin kuljetus samalla urakoitsijalla ja samalla asiakasnumerolla, sitä ei tuoda uudestaan). Viedään kaikki rivit jos ne eivät ole identtisiä. Jos ei muuta eroa kuin PRT, ei viedä.

•	Peräkkäisten kausien kuljetuksia/sopimuksia ei yhdistellä, vaan toistaiseksi jokainen on erillisenä vaikka tiedot olisivat muuten samat. Pitää olla näin.

•	Kohteissa/kuljetuksissa havaittuja rajoitteita:
o	DVV-aineistoissa on joitakin yksittäisiä rakennuksia, joiden kiinteistötunnus tai omistaja on tuntematon. Tällä hetkellä näistä ei luoda kohteita, joten kuljetuksia ei voida tuoda. (Tampereella nämä luodaan uusina kohteina.) On sovittu, että kaikista luodaan kohde, kun rakennus on aiemmin määritellyn mukaan jätehuollon näkökulmasta ns. merkitsevä rakennus.

•	Joillakin rakennuksilla on useampi kohde: paritalot sekä rakennukset, joissa on maksettu useampi perusmaksu. Vaikka prt olisi tiedossa, kuljetuksen kohdentaminen pitää tehdä asukkaan nimellä. Jos asukkaan nimeä ei ole tiedossa tai kuljetuksissa eri nimi, ei voida tuoda. (Tampereella nämä luodaan uusina kohteina.) On sovittu että kohdennetaan käsin.

•	Joissakin kohteissa prt:n/osoitteen omistaja muuttunut vuoden 2021 kuljetusten ja 2022 alkuvuoden dvv-datan välillä. Mitä tehdään?
o	Tällä hetkellä oletetaan, että dvv-kohteet ovat voimassa vuoden 2021 alusta lähtien, joten uudelle asukkaalle/omistajalle merkitään myös rakennusten kaikki viime vuoden kuljetukset, vaikka ne olisi tilattu eri nimellä.
o	Nimeä ei siis yleensä tarkisteta kohdennuksessa. Nimissä liikaa eri kirjoitusasuja => liikaa puuttuvia kohdennuksia. (Tampereella nämä luodaan uusina kohteina.)
o	Eikö sovittu, että kuljetustiedot ja päätökset ja ilmoitukset siirtyvät omistuksen muuttumispäivän mukaisesti uudelle kohteelle?

•	Kuljetustietojen nimi pitää tarkistaa, jos halutaan tulevaisuudessa luoda kuljetustiedoista uusia kohteita, kun nimi muuttuu.
o	Jos kuljetustiedoissa kaksi eri nimeä/asiakasnumeroa kohteelle, tällä hetkellä kummatkin merkitään samalle kohteelle.
o	Tuontikomentoon siis lisättävä uusi parametri: jos eri nimiä/asiakasnumeroita samalla ajanjaksolla, luodaankin uusi kohde
o	Ei haluta luoda kuljetustiedoista kohteita.
