### ISSUE TITLE
Korjaa kuljetustieto-importin akp-rivien käsittely

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#133]
Kuljetustietojen määrittely-xls: 'tyyppiEWC'
Jätelaji: Biojäte, Sekajäte, Kartonkipakkaus, Lasipakkaus, Metallipakkaus, Muovipakkaus
Tästä kentästä on haettavissa, jos on aluekeräys. Viedään kohtaan sopimustyyppi.

Aineistoissa tulee muodossa 'aluekeräyspiste', lisättävä tämän käsittely ('aluekeräys'-muodon lisäksi). Menee jo sopimuksen tyypiksi ja luetaan kuljetukseksi jätelajilla 'muu'.

**Comment by ismogis** [comment]
Muoto on tarkalleen "Aluekeräyspiste", ensimmäinen kirjain isolla.

**Comment by ismogis** [comment]
Ei tehty testiä tallentumiselle kuljetus-tauluun, sillä tietoa ei ilmeisesti tarvita mihinkään.
