### ISSUE TITLE
Lisää monilokeron luku keräysvälinetyypiksi

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#136]
Kuljetustietoaineiston kentässä tyyppiEWC voi vuodesta 2024 eteenpäin tulla tietona 'monilokero'. Näissä tapauksissa keräysväline-tauluun tallennetaan välinetyypiksi 'monilokero'. 

Monilokeroastiassa voi kerätä muovipakkaukset, kartonkipakkaukset, lasipakkaukset ja metallipakkaukset ja niitä käytetään pientaloissa. Ei vaikutusta tämänhetkisten velvoitteiden toteutumiseen.

**Comment by ltalve** [comment]
@AnniinaMet 
Tätä ei ole vielä käsitelty, koska aineistossa ei ole ollut esimerkkiä monilokero-tapauksesta. Pohdimme, että riittääkö määrittelydokumentin mukainen käsittely, eli että luetaan vain 'monilokero' keräysvälinetyypiksi. Vai pitäisikö monilokerorivistä joissakin tapauksissa syntyä myös uusi sopimus. 

Voiko monilokeroastia olla kohteen ainoa astia vai onko kohteella aina oltava myös sekajäteastia? 

Voiko kohde hoitaa sekajätteen velvoitteen olemalla osa kimppaa ja muut velvoitteet omalla monilokerolla? 

Voiko kimpalla olla monilokero?

Mitä tarkoittaa, että monilokerolla ei ole vaikutusta tämänhetkisiin velvoitteisiin?

**Comment by AnniinaMet** [comment]
Näkisin että määrittelyn mukainen käsittely riittää. Näettekö jotakin riskejä, jos siitä ei muodosteta sopimusta?

Monilokeroastia ei voi olla pelkästään, sekajäte ja mahdollinen biojätevelvoite ovat olemassa, vaikka hyötyjätteitä kerättäisiinkin monilokeroon.

Kimppa käy minkä tahansa jätejakeen velvoitteen täyttymiseen.

Monilokero voi olla myös yhteinen jäteastia.

Monilokeroa ei ole palvelutyyppinä tulossa tarjolle kuin pientaloihin ja pientaloilla ei ainakaan toistaiseksi ole velvoitetta kerätä hyötyjätteitä, eli kyse on vapaaehtoisesta keräyksestä.

**Comment by ltalve** [comment]
Kiitos vastauksista @AnniinaMet . @ismogis kysy, jos vielä tulee tähän tarkennustarvetta.

**Comment by AnniinaMet** [comment]
On ajankohtainen

**Comment by tero-punos** [comment]
Siirretty
