### ISSUE TITLE
Asukkaista tulee jossakin tapauksessa osapuolia pmr-kohteessa

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#137]
Tuntematon kohde 50717*: kohteelle muodostuu kohteen ainoan rakennuksen asukkaista osapuolia, vaikka kyseessä on perusmaksurekisterin perusteella muodostettu kohde. Pmr-kohteilla asukkaista ei tule muodostua osapuolia, eikä näin useimmiten näyttäisi käyvänkään. Rakennustyyppi tässä tapauksessa 'ketjutalo', omistajatieto puuttuu dvv-aineistosta.

_*Kohteen numerointi pätee seikan luontihetkellä, mutta jos kohteet joudutaan luomaan myöhemmin uudestaan, numero saattaa muuttua._

**Comment by AnniinaMet** [comment]
Selvitetään onko edelleen validi ongelma

**Comment by tero-punos** [comment]
Siirretty Jira.
