### ISSUE TITLE
Taajama-alueiden päivitys tietokantaan

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#142]
Lisätään shape-tiedostosta uudet rivit tietokantaan. Jos tietokannassa on vastaava vanha rivi ilman loppupäivämäärää, asetetaan tälle loppupäivämääräksi uuden rajauksen alkupäivämäärää edeltävä päivä. Taajama-taulusta ei siis poisteta rivejä, eikä vanhoja rivejä muokata muuten. Mietittävä logiikkaa, jolla loppupäivämääriä asetetaan. Miten tiedetään, mitkä kannan rivit vastaavat vietävän shapen rivejä, kun shape ei sisällä kaikkia taajamia ja toisaalta taajamia saattaa poistua tai tulla lisää?

Toteutuksen yhteydessä tehtävä myös #109

**Comment by AnniinaMet** [comment]
Tullee ajankohtaiseksi, kun taajamarajausta seuraavan kerran päivitetään, ei lähitulevaisuuden suunnitelmissa.
