### ISSUE TITLE
Yhteysvirheen käsittely päätöstietojen viennissä

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#152]
Päätöstietoja vietäessä ei tule virheilmoitusta, jos yhteys kantaan ei toimi, vaan kaikki päätökset jäävät kohdentumatta. Lisätään importteriin virheilmoitus toimimattomasta yhteydestä.

**Comment by AnniinaMet** [comment]
Virheilmoitukselle on tarvetta
