### ISSUE TITLE
Mukauta velvoitemallien tasoryhmittelyä QGIS-projektissa

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#162]
Muokataan QGIS-projektissa seuraavat velvoitetarkistuksia koskevat asiat:
- Niputetaan tasot jätelajeittain niin, että yhdellä tasolla on sellainen ryhmä tietoa, jota on järkevä tarkastella erikseen (kukin jätelaji omalle tasolleen ja alle liikennevalot, velvoiteyhteenvedot samoin kukin omalle tasolleen)
- Siirretään Kohdevelvoitteiden tilanne -taulut pois oletuksena projektissa näkyvissä olevista tasoista, jotta suuren ja nopeasti kasvavan tietomäärän haku ei voi käydä käyttäjältä vahingossa

Samalla varmistetaan, että liikennevalomalli on asetettu näyttämään viimeisin status.

**Comment by ismogis** [comment]
Liikennevalo näyttää viimeisintä statusta, sillä näkymässä jkr.v_velvoitteiden_kohteet on mukana vain viimeisin tallennettu status.
