### ISSUE TITLE
Lisää jkr_editorille oikeus päivittää DVV-aineistoja

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#174]
Lisätään tarvittavat oikeudet, jotta jkr_editor pääsee päivittämään myös DVV-aineistoja.

**Comment by ismogis** [comment]
Koska päivittäessä luodaan tarvittaessa uudet taulut, jkr_editorille tarvitaan oikeus myös uusien taulujen luomiseen.

**Comment by ismogis** [comment]
Import_dvv.sql-funktiossa on huomioitava, ettei editor-roolilla voida muokata admin-roolilla tehtyjä funktioita tai lisätä sarakkeita tauluihin. Ilmeisesti on luotava ryhmärooli (esim. jkr_dvv_admin), joka asetetaan omistajaksi DVV:ssä tarvittaviin funktioihin ja tauluihin. Jkr_admin ja jkr_editor perivät tämän roolin (ei missään tapauksessa päinvastoin). Tällöin jkr_editorille ei tarvitse myöskään antaa erikseen oikeuksia jkr_dvv-skeemaan. Ryhmärooli luodaan ja tarvittavat oikeudet asetetaan uudessa migraatiossa.

**Comment by ismogis** [comment]
Jätetään ilmeisesti tekemättä tässä vaiheessa.

**Comment by ltalve** [comment]
Tässä vaiheessa riittää, että editor voi viedä muita aineistoja kantaan.
