### ISSUE TITLE
Tutki kuljetustiedon tuonnissa vaadittavan tiedontuottajatunnuksen tarve

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#183]
Tutkitaan voidaanko tällä hetkellä kuljetustietojen ajossa vaadittava, manuaalisesti annettava tiedontuottajan tunnus jättää pois. Jos tietoa ei tarvita, poistetaan vaatimus. Tiedontuottajatunnus tulee kuljetustietojen mukana.

**Comment by AnniinaMet** [comment]
Tiedontuottajatunnukselle ei ole tarvetta. Käytämme tälle hetkellä koko ajan omaa tunnustamme.
