### ISSUE TITLE
Ota test-kannasta dump

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#187]
Tehdään test-kannasta dump, jossa on mukana:
- vuoden 2022 kohteet ja niihin tehdyt manuaaliset muokkaukset
- ~~viimeisimmät tietokantamigraatiot~~
- ~~uusin QGIS-versio~~

Dump toimii backupina, jos kanta jouduttaisiin jossain vaiheessa tyhjentämään.

**Comment by ismogis** [comment]
@ltalve Ilmeisesti tietokantamigraatioilla ja QGIS-projektin versiolla ei ole merkitystä, sillä ne saa ajettua helposti uudelleen (kaikki migraatiot sisältäen QGIS-projektin menee muutamassa sekunnissa).

**Comment by ltalve** [comment]
Test-kannasta otettu dump päivämäärällä 20.3.2024. Sisältää 2022 kohteet ja niihin tehdyt manuaaliset muokkaukset. Dumpissa ei ole mukana huoneisto-lkm- eikä taajama-aluerajauksia. 

Tallennetaan tämä versio Lahdelle varmuuskopioksi, johon kanta voidaan palauttaa, jos se pitäisi joskus tulevaisuudessa tyhjentää.
