### ISSUE TITLE
QGIS-projektissa kohteen lomakkeen Velvoitteet-välilehti ei näytä tietoja

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#196]
Ongelma ilmenee dev- ja test-kannoissa, mutta ei kehittäjien lokaaleissa ympäristöissä.

**Comment by ismogis** [comment]
Ongelman selvitys kannattanee aloittaa varmistamalla, että kanta on varmasti kunnossa esim. luomalla uusi QGIS-projekti, johon tuodaan pelkästään kohteen lomakkeen Velvoitteet-välilehdellä tarvittavat taso(t) ja näkymä(t) sekä muodostetaan näistä relaatio. Jos tiedot eivät näy sittenkään, ongelma on projektin sijaan kannan puolella.

**Comment by ltalve** [comment]
Ongelma korjautuu, kun QGIS-projektissa relaation velvoite-v_velvoite_status id-viittaus korjataan. Näkymän id:ksi asetettava velvoite_id.
