### ISSUE TITLE
Korjaa paritalokohteissa DVV-päivityksen yhteydessä ilmenneet virheet

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#197]
Ainakin osa paritalokohteista päättyy DVV päivityksen yhteydessä. Osalle ei muodostu edes uutta kohdetta. Osalle muodostuu myös uusi kohde, ilman muutoksia, tällöin päätökset ja kompostointitiedot jäävät virheellisesti vanhalle kohteelle.

**Comment by AnniinaMet** [comment]
Rakennuksia (PRT), jotka ovat päättyneet, mutta joille ei ole muodostunut uutta kohdetta:
100340235S
1004927398
1005320766
1005414718
100634175P
100929454U
101287154J
1017587422
101892112A
101911954C
101911954C
101911955D
101911956E
1019622915
1020251894
102121088M
102121088M
102207797P
102794873M
1028433757
102901202L
102942129U
102990453N
103071058U
103151753W
103337216K
103535888B
103866074H

Rakennuksia (PRT), joille on muodostunut uusi kohde, vaikka silmämääräisesti siihen ei olisi ollut syytä.
1003867442
1005708543
103170846T
1032090229

**Comment by ismogis** [comment]
Rakennukset (4), joille uusi kohde on muodostunut, eivät ole paritalokohteita.
