### ISSUE TITLE
Tyhjennysvälin pidennyspäätöksen käsittely velvoitetarkistuksessa

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#200]
Velvoitteelle "Sekajäte puuttuu" (id 3) sekä velvoiteyhteenvedolle "Velvoiteyhteenveto ei jätehuoltoa" (id 34) on asetettu ehdoksi, että kohteella ei saa olla voimassa pidennyspäätöstä. Pidennyspäätösehdon voi poistaa, jos palvelua ei ole.

**Comment by AnniinaMet** [comment]
on ajankohtainen ja korjauslistalla
