### ISSUE TITLE
Sekajätteen väärän tyhjennysvälin huomiointi velvoiteyhteenvedossa

### ISSUE THREAD

**Issue by ismogis** [GispoCoding/jkr-lahti#201]
Yhteenvedossa "Velvoiteyhteenveto biojäte puuttuu" (id 35) ei oteta nykyisellään mukaan tapauksia, joissa sekajätteellä on väärä tyhjennysväli. Väärän tyhjennysvälin tapausten lisääminen lienee tarkoituksenmukaista.

**Comment by AnniinaMet** [comment]
Sekajätteen tyhjennysväliongelman tulisi vaikuttaa sekajätteen velvoitteeseen.

**Comment by tero-punos** [comment]
Siirretty Jira
