### ISSUE TITLE
Päätöstietojen kohdennus

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#23]
Kohdennuksen yhteydessä tuotetaan virheraportti, joka koostuu aina ajetun aineiston (yksittäinen tiedosto) kohdentumattomista riveistä.

**Comment by Rikuoja** [comment]
Päätökset on linkitettävä rakennuksiin. Rakennukset voivat siirtyä kohteelta toiselle, kun vanhoja kohteita lakkautetaan ja uusia luodaan.
