### ISSUE TITLE
Perusmaksuaineiston import

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#28]

**Comment by Riikka-S** [comment]
Perusmaksuaineistoa ei ole suunniteltu importoitavan. Ainoastaan käytetään aineistoa apuna kun kohteita luodaan ensimmäisen kerran kerros- ja rivitaloille (toteutussuunnitelman kohta 3) ja vapaa-ajanasunnoille (kohta 7).
