### ISSUE TITLE
Kuljetustietoexcelien importin toteutus

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/jkr-lahti#3]

**Comment by ltalve** [comment]
Lahti tekee kuljetusdatalle käsityötä ennen kuin importoidaan. Vingosta saatavat aineistot ovat omassa formaatissaan ja muualta saatavat omassa formaatissaan.

**Comment by Rikuoja** [comment]
Tässä tekemättä: tallennetaan *kaikki* tulevat rivit ulkoinen asiakastieto -tauluun. Näin kaikki kohteelle tuodut kuljetukset ovat tallessa.

**Comment by TiiaY** [comment]
tallennetaan kaikki tulevat rivit ulkoinen asiakastieto -tauluun kaikille kohteille, jotka ovat kohdentuneet.
**Kyllä**

 Jos tietomallimuutos https://github.com/GispoCoding/jkr-lahti/issues/68 on tehty, voidaan tallentaa myös kohdentumattomat rivit ja niitä voi kohdentaa käsin rivi kerrallaan. Vai riittääkö käyttäjätarinaan https://github.com/GispoCoding/jkr-lahti/issues/40 se, että alkuperäiset excelit ovat tallessa, mutta kohdentumattomia kuljetuksia excelistä ei ole tallennettu tietokantaan?
**Kohdentumattomista raportti ja uusi kohdennusyritys. Riittää että kaikki ei kohdennu.**

 Ulkoinen asiakastieto -tauluun siis lisätään aikaväli, minkä aikavälin kuljetustieto on milloinkin kyseessä. Samalle aikavälille voi edelleen tulla useampia kuljetuksia ja sopimuksia, tallennetaan nämä kaikki.

**Comment by TiiaY** [comment]
@ltalve @Rikuoja 

Miikan tägääminen ei onnistu. Tägäisikö joku?

Aineistot
 
•	Jätehuolto päivittää kuljetustietoaineistot, ei viedä vanhoja.
 
•	Gispon tuottaa ennen aineistojen toimisamista dokumentin/merkitsee kuljetustieto-Exceliin, mitkä tiedot ovat pakollisia ja mitkä tiedot viedään JKR:ään. 
o	UrkId ei tulisi olla pakollinen. 
 
•	Vietävän aineiston dokumentointi: Tehtävä sisäinen ohje miten kuljetustietoja JKR:ään muokataan mikäli se poikkeaa RAKE-muokkauksesta.
 
Kohdistus
 
•	Kohdistus 2021
1.	prt:n perusteella
 
•	Kohdistus 2022 ja eteenpäin
1.	PRT
2.	Urakoitsija ID ja asiakasnumero
3.	Urakoitsija ID ja sama osoite kuin edellisen jakson kuljetustiedoissa.
 
Muuta
 
•	Jätelajit piktogrammijärjestelmän mukaisesti.
 
•	Aluekeräyspisteet viedään sekajätteenä. Sopimustyyppikohtaan aluekeräyspiste. Keskusteltava vielä Gispon kanssa.
 
•	Sysmän kohteet, vrk-tiedot ja kuljetustiedot poistettava.
 
Vastauksia Gispon huoliin
 
•	 Aina kohdetta ei löydy. (Tampereella tämä korjataan luomalla uusi kohde. Tällöin se voi osua päällekkäin jonkun olemassaolevan kohteen kanssa, mutta omistaja tai muut tiedot ovat eri. Meillä ei toistaiseksi luoda uutta kohdetta kuljetustiedoista.) 
->Pitää voida luoda käsin kohde ja kohdentaa käsin.`
•	2021: Osa aineiston riveistä monistuneita, sama tieto tuotu vain kertaalleen (jos tietokannassa on jo saman aikavälin saman jätelajin kuljetus samalla urakoitsijalla ja samalla asiakasnumerolla, sitä ei tuoda uudestaan). 
->Viedään kaikki rivit jos ne eivät ole identtisiä. Jos ei muuta eroa kuin PRT, ei viedä.
•	Peräkkäisten kausien kuljetuksia/sopimuksia ei yhdistellä, vaan toistaiseksi jokainen on erillisenä vaikka tiedot olisivat muuten samat. 
->Pitää olla näin.
•	Kohteissa/kuljetuksissa havaittuja rajoitteita:
o	DVV-aineistoissa on joitakin yksittäisiä rakennuksia, joiden kiinteistötunnus tai omistaja on tuntematon. Tällä hetkellä näistä ei luoda kohteita, joten kuljetuksia ei voida tuoda. (Tampereella nämä luodaan uusina kohteina.) 
->On sovittu, että kaikista luodaan kohde, kun rakennus on aiemmin määritellyn mukaan jätehuollon näkökulmasta ns. merkitsevä rakennus.
•	Joillakin rakennuksilla on useampi kohde: paritalot sekä rakennukset, joissa on maksettu useampi perusmaksu. Vaikka prt olisi tiedossa, kuljetuksen kohdentaminen pitää tehdä asukkaan nimellä. Jos asukkaan nimeä ei ole tiedossa tai kuljetuksissa eri nimi, ei voida tuoda. (Tampereella nämä luodaan uusina kohteina.) 
->on sovittu että kohdennetaan käsin.
•	Joissakin kohteissa prt:n/osoitteen omistaja muuttunut vuoden 2021 kuljetusten ja 2022 alkuvuoden dvv-datan välillä. Mitä tehdään?
o	Tällä hetkellä oletetaan, että dvv-kohteet ovat voimassa vuoden 2021 alusta lähtien, joten uudelle asukkaalle/omistajalle merkitään myös rakennusten kaikki viime vuoden kuljetukset, vaikka ne olisi tilattu eri nimellä.
o	Nimeä ei siis yleensä tarkisteta kohdennuksessa. Nimissä liikaa eri kirjoitusasuja => liikaa puuttuvia kohdennuksia. (Tampereella nämä luodaan uusina kohteina.)
-> Eikö sovittu, että kuljetustiedot ja päätökset ja ilmoitukset siirtyvät omistuksen muuttumispäivän mukaisesti uudelle kohteelle?
•	Kuljetustietojen nimi pitää tarkistaa, jos halutaan tulevaisuudessa luoda kuljetustiedoista uusia kohteita, kun nimi muuttuu.
o	Jos kuljetustiedoissa kaksi eri nimeä/asiakasnumeroa kohteelle, tällä hetkellä kummatkin merkitään samalle kohteelle.
o	Tuontikomentoon siis lisättävä uusi parametri: jos eri nimiä/asiakasnumeroita samalla ajanjaksolla, luodaankin uusi kohde
-> Ei haluta luoda kuljetustiedoista kohteita.

**Comment by ltalve** [comment]
Jätelajit ovat piktogrammin mukaan seuraavat:
- Muovi
- Metalli
- Lasi
- Paperi
- Biojäte
- Sekajäte
- Kartonki

Tällä hetkellä jätelajit ovat koodistossa seuraavat:
    (1,'Biojäte'),
    (2,'Sekajäte'),
    (3,'Kartonki'),
    (4,'Lasi'),
    (5,'Liete'),
    (6,'Mustaliete'),
    (7,'Harmaaliete'),
    (8,'Metalli'),
    (9,'Muovi'),
    (10,'Pahvi'),
    (11,'Paperi'),
    (12,'Perusmaksu'),
    (13,'Energia'),
    (99,'Muu')

Kaikki piktogrammin mukaiset jätelajit löytyvät listasta. Täytyykö jotain muuttaa @TiiaY ?

**Comment by TiiaY** [comment]
@ltalve  pitäisi vielä olla energiajäte, mutta ehkä tuon energian kanssa voi elää. Pitää keskustella miten olette vieneet aluekeräyspisteet, koska ne ovat meidän aineistossa ollut jätelaji aiemmin.

**Comment by ltalve** [comment]
@TiiaY Jätelajeista on oma seikka täällä, joten siirrän keskustelun sinne: https://github.com/GispoCoding/jkr-lahti/issues/72

**Comment by ltalve** [comment]
Kohteissa on tehty paljon muutoksia syksyllä tehdyn ensimmäisen kuljetustietoimportin jälkeen. Täytyy selvittää mitkä osat siinä toimivat ja mitä täytyy muuttaa, jotta kuljetustiedot lähtevät kohdentumaan oikein uuden logiikan mukaan luoduille kohteille.

**Comment by TiiaY** [comment]
@ltalve @Rikuoja. Miikkaa ei voi tägätä.

Ennen kuljetustietojen uudelleen viemistä tai scripitin miettimästä tulee olla yhteisesti selvää
- Mitä sarakkeita kulejtustieto-Exceleistä viedään ja minne JKR tauluihin ja millä otsikolla. -> Gispo toimittaa dokumentin.
- Mitkä tierdot ovat JKR:n kannalta pakollisia ja miksi. -> Gispo toimittaa dokumentin.

**Comment by ltalve** [comment]
Siirretty seikasta #77 

**Mitä sarakkeita kuljetustieto-Exceleistä viedään ja minne JKR-tauluihin ja millä otsikolla.**

Kuljetustieto-excelistä viedään datat tietokannan tauluihin tällä hetkellä seuraavasti:

- UrakoitsijaId - jkr.kuljetus:tiedontuottaja_tunnus, jkr.osapuoli:tiedontuottaja_tunnus, jkr.sopimus:tiedontuottaja_tunnus, jkr.ulkoinen_asiakastieto:tiedontuottaja_tunnus
- x-koordinaatti - ei lueta
- y-koordinaattori - ei lueta
- Eranro - ei lueta
- UrakoitsijankohdeId - jkr.ulkoinen_asiakastieto:ulkoinen_id
- Rakennustunnus/Kiinteistotunnus - ei lueta
- Kiinteistonkatuosoite - jkr.osapuoli:katuosoite
- Kiinteistonposti - jkr.osapuoli:katuosoite, jkr.osapuoli:postipaikka, jkr.osapuoli:postinumero
- kimppa - ei lueta
- kimppaid - ei lueta
- Haltijannimi - jkr.osapuoli:nimi
- Haltijanyhteyshlo - jkr.osapuoli:nimi
- Pvmalk - jkr.kuljetus:alkupvm
- Pvmasti - jkr.kuljetus:loppupvm
- tyyppiIdEWC - jkr.kuljetus:jatetyyppi_id, jkr.sopimus:jatetyyppi_id
- COUNT(kaynnit) - jkr.kuljetus:tyhjennyskerrat
- SUM(astiamaara) - jkr.keraysvaline:maara
- koko - jkr.keraysvaline:tilavuus, jkr:kuljetus:tilavuus
- SUM(paino) - jkr.kuljetus:massa
- tyhjennysvali - jkr.tyhjennysvali:tyhjennysvali
- kertaaviikossa - ei lueta
- Voimassaoloviikotalkaen - jkr.tyhjennysvali:alkuvko
- Voimassaoloviikotasti - jkr.tyhjennysvali:loppuvko
- Voimassapvmalkaen - ei lueta
- Voimassapvmasti - ei lueta
- Voimassaoloviikotalkaen2 - ei lueta
- Voimassaoloviikotasti2 - ei lueta
- tyhjennysvali2 - ei lueta
- kertaaviikossa2 - ei lueta
- PalveluKuuluukokimppaan - ei lueta
- Kimpanjakoosuus - ei lueta
- palveluKimppakohdeId - kts. alla
- KimpanNimi - kts. alla
- Kimpasta vastaava - ei lueta
- Kimpankatuosoite - kts. alla
- Kimpanposti - kts. alla
- Keskeytysalkaen - ei lueta
- Keskeytysasti - ei lueta

Jos kuljetukselle on täytetty kentät palveluKimppakohdeId, KimpanNimi, Kimpankatuosoite ja Kimpanposti, sitä käsitellään kimppaan kuuluvana. Jokaiselle kimppaan kuuluvalle sopimukselle lisätään oma rivi jkr.sopimus-tauluun, jossa sopimukset linkitetään kimppaisäntään. Merkitsevät kentät ovat seuraavat.

- palveluKimppakohdeId
- KimpanNimi
- Kimpankatuosoite
- Kimpanposti

Lisäksi tauluun jkr.ulkoinen_asiakastieto kenttään ulkoinen_asiakastieto tallennetaan json-muodossa seuraavat sarakkeet:

- UrakoitsijaId
- UrakoitsijankohdeId
- Kiinteistonkatuosoite
- Kiinteistonposti
- Haltijannimi
- Haltijanyhteyshlo
- Haltijankatuosoite
- Haltijanposti
- Haltijanmaakoodi
- Haltijanulkomaanpaikkakunta
- Pvmalk
- Pvmasti
- tyyppiIdEWC
- COUNT(kaynnit)
- SUM(astiamaara)
- koko
- SUM(paino)
- tyhjennysvali
- Voimassaoloviikotalkaen
- Voimassaoloviikotasti
- palveluKimppakohdeId
- KimpanNimi
- Kimpankatuosoite
- Kimpanposti
- Kuntatun

-----
Jätehuollon huomioita Kuljetustieto-excelistä vietävään dataan:

- Rakennustunnus/Kiinteistotunnus - ei lueta
Tämä pitäisi kyllä lukea sisään, koska sen perusteella tieto kohdentuu. Ei sille ole välttämätöntä paikkaa olla, mutta rakennus id tulee tietoa vietäessä huomioida.

- Haltijanyhteyshlo - jkr.osapuoli:nimi
Ei ole tarpeen viedä tietokantaan

- SUM(paino) - jkr.kuljetus:massa
Nykyisen määrittelyn mukaisesti ei ole tarpeen lukea sisään, mutta tuota kyllä saatetaan myöhemmin tarvita lietekuljetustiedoissa, eli on sille hyvä varata nyt jo poikka. Kuljetustietojen muoto on kuitenkin likimain sama

- kertaaviikossa - ei lueta
Tämä on määritelty luettavaksi ja sille pitäisi löytyä paikka.

- Voimassaoloviikotalkaen2 - ei lueta
- Voimassaoloviikotasti2 - ei lueta
- tyhjennysvali2 - ei lueta
- kertaaviikossa2 - ei lueta
Näistä kaikki pitäisi lukea sisään ja niille pitäisi löytyä paikka. Kyseessä on tapaukset, joissa asiakkaalla on kaksi eri rytmiä.

- Keskeytysalkaen - ei lueta
- Keskeytysasti - ei lueta
Nämä tulee lukea sisään ja nille tulee löytyä paikka

- KimpanNimi
Kimpan nimi ei ole jätehuollolle olennaista tietoa, eikä sitä jätehuollon määrittelyn mukaan ole tarpeen viedä kantaan. Jos siitä kuitenkin on apua kimpan käsittelyssä tietokannassa, niin toki sen voi viedä. Kimpan yhteyshenkilöntieto, eli "kimpasta vastaava" sen sijaan tulee olla tietokannassa nähtävissä ja sieltä saatavissa.

**Taulu jkr.ulkoinen_asiakastieto**

- Haltijanyhteyshlo
Ei ole tarpeen viedä tietokantaan
- KimpanNimi
Kimpan nimi ei ole jätehuollolle olennaista tietoa, eikä sitä jätehuollon määrittelyn mukaan ole tarpeen viedä kantaan. Jos siitä kuitenkin on apua kimpan käsittelyssä tietokannassa, niin toki sen voi viedä. Kimpan yhteyshenkilöntieto, eli "kimpasta vastaava" sen sijaan tulee olla tietokannassa nähtävissä ja sieltä saatavissa.

Jos tässä taulussa on kuljetustietoa, kuten tyhjennysvälit ja käyntimäärät, niin myös seuraaville tiedoille tullee löytyä paikka:
- Voimassaoloviikotalkaen2
- Voimassaoloviikotasti2
- tyhjennysvali2
- kertaaviikossa2

**Comment by ltalve** [comment]
Siirretty seikasta #77 

### Mitkä tiedot ovat JKR:n kannalta pakollisia ja miksi.

**Pakolliset tiedot (ei saa olla tyhjä millään rivillä)**

UrakoitsijaID - yksilöi urakoitsijan
Pvmalk - kvartaalin alku
Pvmasti - kvartaalin loppu
tyyppiIdEWC - https://github.com/GispoCoding/jkr-lahti/issues/48
COUNT(kaynnit) - velvoitteiden toteutuminen (voi olla 0)

**Vaihtoehtoiset tiedot kohdentamiseen**

a) Rakennustunnus / Kiinteistotunnus
b) Kiinteistonkatuosoite + Kiinteistonposti

**Comment by ltalve** [comment]
Tämä käytävä vielä läpi ja tarkastettava, että tarvittava tieto menee kantaan.

**Comment by ismogis** [comment]
Kommentit listaan **Jätehuollon huomioita Kuljetustieto-excelistä vietävään dataan** (https://github.com/GispoCoding/jkr-lahti/issues/3#issuecomment-1789344308):

- Rakennustunnus/Kiinteistotunnus
-- Tietoa käytetään kohdentamiseen, mutta sitä ei tallenneta.

-  Haltijanyhteyshlo
-- Tietoa ei viedä enää tietokantaan, sillä yhteyshenkilö ei ole enää kohteen osapuolena.

- SUM(paino)
-- Tieto luetaan nyt jkr.kuljetus-taulun sarakkeeseen massa. Poistetaanko luku eli jätetäänkö sarake toistaiseksi tyhjäksi?

**Comment by ismogis** [comment]
@ltalve 

Näistä tulee ainakin seuraavat seikat (lisäksi vielä yksi riippuen vastauksesta kysymykseen 1 yllä):

1. Muokataan tyhjennysväli-taulua (myös tietomallissa) siten, että sinne voi tallentaa myös kertaaviikossa-tiedon. Yksi vaihtoehto on vaihtaa tyhjennysväli liukuluvuksi.

2. Luetaan tyhjennysväli-tauluun edellisessä kommentissa mainitut asiat.

3. Muokataan sopimus-taulua (myös tietomallissa) siten, että sinne voi tallentaa myös keskeytyksen alun ja lopun.

4. Luetaan sopimus-tauluun keskeytykset.

**Comment by AnniinaMet** [comment]
@ismogis @ltalve @TiiaY 
**Tässä Vastauksia:**
Sarake SUM(paino) luetaan nyt jkr.kuljetus-taulun sarakkeeseen massa. Poistetaanko luku kiinteälle jätteelle eli jätetäänkö sarake toistaiseksi tyhjäksi?
- Pidetään sarake mukana, mutta se tosiaan jää kiinteällä jätteellä tyhjäksi.

Voiko asiakkaalla olla enemmän kuin tyhjennysrytmiä? Eli voiko kuljetustieto-excelissä olla esim. tyhjennysvali3 ja kertaaviikossa3?
- Tyhjennysrytmejä voi toki olla lukematon määrä, mutta yhdellä asiakastietorivillä voi olla maksimissaan kaksi rytmiä. Mikäli asiakkaalla olisi useampia rytmejä, niin silloin seuraavat kaksi tulevat taas omana rivinään. Eli yhdellä kuljetustietorivillä ei voi olla kuin kaksi rytmiä.

Jos kertaaviikossa-kentällä on arvo, onko tyhjennysväli silloin aina 1?
- Kyllä, näin pitäisi olla. Voidaan vielä tarkentaa meidän aineistojen käsittelyohjeeseen, että tuo pitää tarkastaa.

**Comment by ismogis** [comment]
Näistä tehty seuraavat seikat:

#119 
#120 
#121 
#122 (Huom! Niputin tähän kohdat 3 ja 4 kommentissa https://github.com/GispoCoding/jkr-lahti/issues/3#issuecomment-1898426706, pitäisi olla pikkujuttu)

**Comment by ltalve** [comment]
_Mitä sarakkeita kuljetustieto-Exceleistä viedään ja minne JKR-tauluihin ja millä otsikolla.
Kuljetustieto-excelistä viedään datat tietokannan tauluihin tällä hetkellä seuraavasti:
[...]
tyyppiIdEWC - jkr.kuljetus:jatetyyppi_id, jkr.sopimus:jatetyyppi_id_

Määrittely-xls: 'tyyppiEWC'
_Jätelaji: Biojäte, Sekajäte,  Kartonkipakkaus, Lasipakkaus,  Metallipakkaus, Muovipakkaus
Tästä kentästä on haettavissa, jos on aluekeräys. Viedään kohtaan sopimustyyppi. 
Tästä kentästä on haettavissa, jos on monilokero, viedään kohtaan keräysvälinetyyppi._


**Näin ollen em. rivin pitäisi oletettavasti olla:**
tyyppiIdEWC - jkr.kuljetus:jatetyyppi_id, jkr.sopimus:sopimustyyppi_id, jkr.keraysvaline:keraysvalinetyyppi_id

Keräysvälinetyypiksi on lisättävä 'monilokero', jota ei toistaiseksi taida olla.

@ismogis @Mtk112 Jos olette samaa mieltä, tehdään uusi seikka => #133
