### ISSUE TITLE
Erota testi- ja kehitysympäristö toisistaan

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#67]
Tulee tehdä varmuuskopioitu tietokantaympäristö, ennen kuin Lahdessa aletaan tuottaa pysyvää sisältöä tietokantaan.

Kehitystietokannan tulee olla jatkossakin kehittäjien testattavissa niin, että dataa saa tuhoutua, eikä siellä saa olla korvaamatonta/uutta tietoa.

Testitietokannan tulee olla varmuuskopioitu, testitietokantaan päivitetään uutta sisältöä ja tehdään muokkauksia jatkuvasti, ja näiden tietojen pitää säilyä. Näin tuotuja kuljetuksia ja kohteita voidaan käyttää seuraavan kvartaalin ja seuraavan vuoden datan tuonnin pohjana. Testitietokantaa ei saa tyhjentää kehityksen yhteydessä.

**Comment by TiiaY** [comment]
Ei odota vastausta Lahdelta?

**Comment by TiiaY** [comment]
Luvattu Fujitsulta 9.2.

**Comment by Rikuoja** [comment]
@TiiaY Kiitos, odottelemme tietoja tuosta toisesta tietokantaympäristöstä niin päästään kokeilemaan sitä!

**Comment by ltalve** [comment]
Issue voidaan merkitä tehdyksi, kun kohteet on viety palvelimella kantaan ja testiympäristö on käytössä.

**Comment by ltalve** [comment]
Testiympäristöön luotava Lahdelle admin-käyttäjä, joka saa tehtyä muokkauksia työtilaan (esim. taustakartat).

**Comment by ltalve** [comment]
Kysymys: @TiiaY @AnniinaMet näyttävätkö dev-palvelimella olevat kohteet nyt oikeilta (viimeinen korjaus liittyi pm-rekisteriaineiston päivitykseen)?

Jos kyllä, voidaan siirtää samat kohteet testipalvelimelle ja sulkea sen jälkeen tämä seikka.

**Comment by TiiaY** [comment]
@ltalve @AnniinaMet @ismogis Anniina katsoo alkuviikosta.

**Comment by AnniinaMet** [comment]
Kohteet näyttää luodun määrittelyiden mukaisesti, joten kohteet voi päivittää testipalvelimelle.

**Comment by ltalve** [comment]
@AnniinaMet @TiiaY Esille noussut kohteiden nimiasia (oudot nimet) johtuu siitä, että tällä hetkellä kohteiden nimeksi tulee satunnainen asukkaan nimi. Mikä nimi kohteille mainituissa tapauksissa haluttaisiin?

**Comment by AnniinaMet** [comment]
@ltalve Omistajan nimi, kuten kaikilla viereisilläkin kohteilla ja noin 99,5% muistakin kohteista.

**Comment by ltalve** [comment]
Siirrän keskustelun kohteiden nimeämislogiikasta Seikkaan #22
