### ISSUE TITLE
Jokaisen kuljetuksen ja sopimuksen prt talteen

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#68]
Käyttäjätarina https://github.com/GispoCoding/jkr-lahti/issues/45 vaatii, että kuljetukset ja sopimukset ovat listattavissa kohteiden lisäksi rakennuksittain.

Kuljetustietojen tuonnin yhteydessä on siis tallennettava ylimääräiseen kenttään, mitä kohteen rakennusta tuotu rivi alunperin koski. 

~~Tämä tieto on saatavissa myös alkuperäisissä kuljetustiedoissa (Ulkoinen asiakastieto), mutta oikean rivin etsiminen jsonista kuljetuksen tai sopimuksen perusteella ei onnistu, joten rakennustunnus on parempi tallentaa suoraan kuljetukseen/sopimukseen.~~

TAI

~~Koska kuljetuksia/sopimuksia halutaan listata rakennuksittain, *jokaisesta* rakennuksesta on tehtävä oma kohteensa. Eli toisin sanoen, koko kohteidenluontilogiikka on turha.~~

TAI

Jokainen kuljetus liitetään kohteen sijaan vastaavaan sopimukseen. Jokainen sopimus liitetään kohteen lisäksi "Ulkoinen asiakastieto"-tauluun, niin että nähdään, mistä asiakastietorivistä sopimus (ja kuljetus) on lähtöisin. Samassa myös osapuoliin liitetään "Ulkoinen asiakastieto". Näin kaikki tuodut tiedot on linkitetty suoraan alkuperäiseen asiakastietoriviin. Tätä tarvitaan kuljetustietojen siirtämiseen uusille kohteille, eli käyttäjätarinoihin https://github.com/GispoCoding/jkr-lahti/issues/62 ja https://github.com/GispoCoding/jkr-lahti/issues/59

**Comment by TiiaY** [comment]
Ei tarvitse. Riittää, että kuljetus näkyy kohteella ja kaikki kuljetusyrityksen ilmoittamat tiedot.

**Comment by Rikuoja** [comment]
Toteutetaan siis tämä tietomallimuutos siinä vaiheessa, kun on tarve tarkastella alkuperäisiä kuljetusrivejä kuljetuksittain/rakennustunnuksittain/osoitteittain. Ei tarvitse tehdä heti.

**Comment by TiiaY** [comment]
Onko kuitenkin mahdollista saada tässä vaiheessa ulos raportti, jossa on kohteen jokainen rakennus eri rivinä ja kohteen kuljetustieto perässä? Eli sama kuljetustieto.  Ympäristönsuojeluviranomaiset haluat tiedot rakennuksittain.

**Comment by ltalve** [comment]
@AnniinaMet @TiiaY
Tarvitaanko siis tieto siitä, mille kohteen rakennukselle mikäkin kuljetus kuuluu? Mihin tieto tarvitaan?

Jos tieto tarvitaan (esim. ympäristöviranomaiselle ei riitä alkuperäinen kuljetustietoaineisto, jossa kuljetustieto on rakennuksittain), selkein olisi, jos voitte tehdä tästä raporttimallin (xls).

**Comment by ltalve** [comment]
12.1.2024 päätetty, että rakennustietoa ei tarvita kohteen kuljetustiedoissa.
