### ISSUE TITLE
Testaa ja tarvittaessa korjaa kuljetustietojen päivittyminen

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#69]
Kokeiltava, miten kuljetustiedot päivittyvät, kun uuden kvartaalin kuljetustiedot tulevat saataville.

Tarkistettava, että päivämäärät ja kuljetusten alku- ja loppuajat tallentuvat oikein.

Tampereella peräkkäiset sopimukset yhdistetään. Lahdessa halutaan kaikki kuljetus- ja sopimustiedot omiksi riveikseen kvartaaleittain.

**Comment by ltalve** [comment]
Suljettu historiallinen seikka tarpeettomana. Testaus ja korjaukset omissa seikoissaan.
