### ISSUE TITLE
Kohteiden luonnin ja DVV-päivityslogiikan dokumentaatio

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#70]
Tehtyyn dokumentaatioon lisättävä osuus, joka ohjeistaa dvv-kohteiden tuontiin ja päivittämiseen. Tampereen ohjeessa tätä osiota ei ole, koska Tampereella kohteet luodaan kuljetustiedoista.

**Comment by TiiaY** [comment]
Ei odota vastausta Jätehuollolta?

**Comment by ltalve** [comment]
Dokumentaatiossa kuvattava selvästi myös manuaalisesti muokattujen kohteiden käyttäytyminen aineistopäivityksen yhteydessä.
