### ISSUE TITLE
Lisää Lahdelle omat jätelajien nimet

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#72]
Käyttäjätarinassa #48 halutaan ilmeisesti käyttää Lahden omia jätelajien nimiä, eikä coressa käytettyjä:

Aluekeräyspiste
		
Biojäte
		
Energiajäte
		
Kartonkipakkaus
		
Lasipakkaus
		
Metallijäte
		
Muovipakkaus

**Comment by Rikuoja** [comment]
Tehdäänkö migraatio lahti-moduuliin? Voiko aiheuttaa ongelmia coreen?

**Comment by TiiaY** [comment]
@Rikuoja @ltalve Onko tässä jätehuollolle avoimia kysymyksiä?

**Comment by ltalve** [comment]
Lahden toivomat jätelajien nimet (jätehuollon piktogrammit -tiedoston perusteella): 
Biojäte
Lasi
Paperi
Kartonki
Muovi
Metalli
Sekajäte

**Comment by TiiaY** [comment]
Paperia emme tarvitse, muuten ok.
