### ISSUE TITLE
Lisää Lahdelle omat osapuolten roolit

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#73]
Lahdelta tullut toive tallentaa seuraavia osapuolten rooleja:

**Vanhin asukas** 
Lähde: DVV
Prosessi josta tieto saadaan: uusi DVV:n aineisto viedään tietokantaan (vuosittain)	
Nimi ja osoite
	
**Asukas**
Lähde: DVV tai Trimble
Prosessi josta tieto saadaan: uusi DVV:n tai Trimblen asukasaineisto viedään tietokantaan (vuosittain)
Nimi ja osoite
	
**Omistaja**
Lähde: DVV
Prosessi josta tieto saadaan: uusi DVV:n aineisto viedään tietokantaan (vuosittain)
Nimi ja osoite
	
**Sekajätteen tilaaja**
Lähde: Kuljetustiedot
Prosessi josta tieto saadaan: kuljetustiedot viedään tietokantaan ( kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

**Energiajätteen tilaaja**	
Lähde: Kuljetustiedot
Prosessi josta tieto saadaan: kuljetustiedot viedään tietokantaan ( kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)
	
**Pakkaus- ja biojätteen tilaaja**
Lähde: Kuljetustiedot
Prosessi josta tieto saadaan: kuljetustiedot viedään tietokantaan ( kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)
	
**Akp-tilaaja**
Lähde: Kuljetustiedot
Prosessi josta tieto saadaan: kuljetustiedot viedään tietokantaan ( kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

**Lietteen kuljetuksen tilaaja**
Lähde: Kuljetustiedot
Prosessi josta tieto saadaan: kuljetustiedot viedään tietokantaan ( kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)
	
**Kimppaisäntä**
Lähde: Kimppailmoitus
Prosessi josta tieto saadaan: Kimppa mastertieto viedään tietokantaan (tietojen vientisykli tarkentuu myöhemmin)
Nimi, osoite, sähköposti

**Kimppaosakas**
Lähde: Kimppailmoitus
Prosessi josta tieto saadaan: Kimppa mastertieto viedään tietokantaan (tietojen vientisykli tarkentuu myöhemmin)
Nimi, osoite, sähköposti

**Comment by Rikuoja** [comment]
Missä vaiheessa nämä roolit pitää toteuttaa? Mihin käyttäjätarinaan erilaiset roolit liittyvät eli missä niitä tarvitaan?

Mihin repoon roolit toteutetaan, ts. miten muutetaan alkuperäistä koodia https://github.com/GispoCoding/jkr-core/blob/main/jkrimporter/providers/db/services/osapuoli.py , joka tällä hetkellä luo osapuolet "Asiakas" ja "Yhteystieto"?

**Comment by TiiaY** [comment]
Me tarvitsemme ainakin kontaktointia varten asukkaan, omistajan, mahdollisen päätöksen yhteyshenkilön ja kuljetussopimuksen tekijän tiedot. Tästä olisi hyvä keskustella, mikä on vaikeaa ja mikä helppoa toteuttaa (hinta).

**Comment by Rikuoja** [comment]
Joillakin näistä osapuolista voi ilmeisesti olla myös voimassaoloaikoja, jotka ovat eri kuin kohteen voimassaolo. Eli osapuolitauluun voidaan joutua lisäämään voimassaoloaikoja sitten, kun näitä osapuolten rooleja toteutetaan.

**Comment by Rikuoja** [comment]
Kaikki kohteen rakennusten omistajat ja vanhimmat asukkaat on tietysti löydettävissä kontaktointia varten myös yksittäisten rakennusten kautta.

Mutta tässä kyse on nyt siitä, kuka tai ketkä näistä dvv-omistajista ja vanhimmista asukkaista halutaan merkitä jollain erityisroolilla suoraan *myös* kohteen vastuuosapuoleksi.

Eli halutaanko tuontilogiikan perusteella valita joku asukas tai omistaja erityisasemaan, jolle tehdään erillinen linkitys kohteeseen, ja millä perusteella? Vai riittääkö katsoa rakennusten omistajia/asukkaita ja päätellä sieltä keneen ottaa yhteyttä?

**Comment by TiiaY** [comment]
@Rikuoja @LKajan @ltalve 

Käyttäjätarina 14

 https://lahti.sharepoint.com/:w:/r/sites/LahtiJtehuollonjrjestelmprojekti-Scrum-tiimi/Jaetut%20asiakirjat/Scrum-tiimi/K%C3%A4ytt%C3%A4j%C3%A4tarinat/Lahden%20k%C3%A4ytt%C3%A4j%C3%A4tarinat%20Lahden%20kommentoima%209.1.2023.docx?d=w683fa410709c4ddfad3e1ceb8a74de90&csf=1&web=1&e=TbZdVF

**Comment by Rikuoja** [comment]
@TiiaY Käyttäjätarinassa sanotaan seuraavaa:

> Raportille tarvitsen esimerkiksi seuraavat tiedot: kohdeid, PRT, velvoitteiden täyttyminen, kuntaurakka-alue/kiinteistönhaltijan alue, taajama-alue vai muu alue, kohteen rakennusten käyttötarkoituksen, kohteen rakennuksen käyttötila, osoite, kuntatunnus, jätehuollon tilaajan nimi ja yhteystiedot, asukas, omistaja ja yhteystiedot. Yksi rivi/rakennus.

Meillähän on jo kaikilla rakennuksilla omistajat ja asukkaat. Kysymys tässä koski sitä, halutaanko *joku näistä* rakennuksen omistajista/asukkaista lisätä lisäksi suoraan *kohteelle* osapuoleksi jotain käyttötarkoitusta varten?

Käyttäjätarina 14 on rakennuskohtainen, se onnistuu jo. Eli mihin näitä kohdekohtaisia osapuolia tarvitaan?

**Comment by Rikuoja** [comment]
Tässä siis kuva. Tässä keskustellaan siitä, millaisia ylimääräisiä linkityksiä halutaan luoda osapuolten ja kohteen välille.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/9367712/223483588-3115ed6d-4e51-4d21-8b24-9ad9535a6fb5.png">

**Comment by Rikuoja** [comment]
Tulkitsen tästä, että uusiksi osapuolten rooliksi pitäisi saada ainakin "kuljetussopimuksen tekijä" ja "päätöksen yhteyshenkilö". Omistajat ja vanhemmat löytyvät jo tietokannasta rakennusten kautta, niin niille ei välttämättä tarvitse heti tehdä erillisiä rooleja kohteelle.

**Comment by Rikuoja** [comment]
Jos löytyy *kohdekohtaisia* (ei rakennuskohtaisia) raportteja, joihin pitää valita *etukäteen* jonkun säännön mukaan joku/jotkut kohteen rakennuksen omistajista *erikseen*, sitten voi olla mielekästä lisätä kohderaportteja varten joku tietty omistaja/asukas raportin yhteyshenkilöksi suoraan kohteelle?

**Comment by ltalve** [comment]
Kysymys on @TiiaY:

Tällä hetkellä kohteella on roolit "asiakas" ja "yhteystieto". Ovatko näiden lisäksi tarvittavat roolit "kuljetussopimuksen tekijä/jätehuollon tilaaja" ja "päätöksen yhteyshenkilö" (kuten Riku ylempänä esittää), vai tarvitaanko kaikki issuen alussa listatut osapuolen roolit?

**Comment by TiiaY** [comment]
@ltalve @ismogis Milloin tarvitsette vastauksen tähän asiaan?

**Comment by ltalve** [comment]
@TiiaY Tällä ei ole vielä tässä vaiheessa meidän puolesta kiire. Rooleja voidaan mielestäni katsoa siinä vaiheessa, kun niille ilmenee tarve. Voidaan poistaa tässä vaiheessa tuo kysymys-tagi.

**Comment by ltalve** [comment]
@TiiaY  @AnniinaMet 
Tämä kysymys nousi nyt kuitenkin esille kohteiden luonnin ja päivityksen yhteydessä. Kuten tuossa ylempänä jo mainittiin, rakennuksilla on omistajat ja vanhimmat asukkaat. Osapuolet taas ovat kohdekohtaisia (vrt. QGISin kohdelomake ja siellä välilehti 'Osapuolet'). Tämän seikan ensimmäisen osapuolten roolilistan osalta tässä vaiheessa olisi hyvä saada selvyys seuraaviin:

**Omistaja:** jos kohteella on useampia rakennusten omistajia, saavatko kaikki kohteella roolin 'omistaja'? Jos eivät, millä perusteella yksi omistaja valitaan?

**Vanhin asukas:** jos kohteen rakennuksissa on useampi 'vanhin asukas', millä perusteella näistä valitaan kohteelle vain yksi?

**Asukas:** halutaanko osapuoli-välilehdelle listatuksi kaikki kohteen rakennuksissa asuvat asukkaat? Tarvitaanko tieto siis jostakin syystä erikseen, vaikka se on jo saatavissa rakennusten kautta?

@Mtk112 @ismogis

**Comment by TiiaY** [comment]
@ltalve @Mtk112 @ismogis 

Omistaja: Kaikki kohteen rakennusten omistajat saavat roolin omistaja. Määrittelyiden mukaan kohteen rakennuksilla pitää olla samat ommistajat,

Vanhin asukas: Vanhin asukas tulee kohteille, joissa yksi asuttu huoneisto. Muille kohteille ei tule asukkaita osapuoliksi. 
- esimerkiksi kohteella on rivitalo, jossa on 2 rakennusta ja yhtensä 4 huoneistoa. Kaikissa on eri vanhin asukas. Kohteelle ei tule osapuoleksi asukkaita,
- esimerkiksi kohteella on saman omistajan 2 asuinrakennusta, Yhdessä rakennuksessa asutaaan ja toinen on tyhjillään. Kohteelle tulee osapuoleksi vanhin asukas.
- tulee huolehtia, että asutut paritalohuoneistot on omina kohteina. Nyt niissä on joissakin ongelmia..

Asukas: Meillä ei ole asukkaita, on vain huoneiston vanhin asukas.. Meillä ei ole osapuolta asukas.

**Comment by ltalve** [comment]
Asukas ja omistaja lisätty osapuolen rooleiksi. Myöhemmissä vaiheissa lisätään tarpeelliset muut osapuolet omina seikkoinaan.

**Comment by ismogis** [comment]
> Tulkitsen tästä, että uusiksi osapuolten rooliksi pitäisi saada ainakin "kuljetussopimuksen tekijä/jätehuollon tilaaja?" ja "päätöksen yhteyshenkilö".
> 
> Omistajat ja vanhemmat löytyvät jo tietokannasta rakennusten kautta, niin heille ei välttämättä tarvitse heti tehdä erillisiä rooleja kohteelle. Tällä hetkellä heidätkin lisätään rooleilla "asiakas" ja "yhteystieto", näitä voidaan muuttaa niin etteivät mene sekaisin "kuljetussopimuksen tilaajan" ja "päätöksen yhteyshenkilön" kautta.

Tämä Rikun tulkinta vaikuttaa edelleen pätevältä. Eli kuljetustietoja varten tarvittaisiin yksi rooli lisää: "kuljetussopimuksen tekijä/jätehuollon tilaaja".

**Comment by ltalve** [comment]
Osapuolen rooleista tehty 31.10.2023 uusi päivitetty listaus (alla). Tätä seikkaa ei enää päivitetä, vaan roolien toteutuksesta järjestelmään tehdään aineistokohtaisesti uudet seikat työn edetessä.

Asukas
Lähde: DVV
Prosessi, josta tieto saadaan: uusi DVV:n asukasaineisto viedään tietokantaan (vuosittain)
Nimi ja osoite

Omistaja
Lähde: DVV
Prosessi, josta tieto saadaan: uusi DVV:n aineisto viedään tietokantaan (vuosittain)
Nimi ja osoite

**TILAAJAT**
Tilaaja sekajäte
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja biojäte
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja muovipakkaus
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja kartonkipakkaus
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja lasipakkaus
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja metalli
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja monilokero (ei vielä ole kuljetuksissa)
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Tilaaja liete
Lähde: Kuljetustiedot
Prosessi, josta tieto saadaan: kuljetustiedot viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

**KIMPPAISÄNNÄT**
Kimppaisäntä sekajäte
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

Kimppaisäntä biojäte
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

Kimppaisäntä muovipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

Kimppaisäntä kartonkipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

Kimppaisäntä lasipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

Kimppaisäntä metalli
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Kimpanyhteyshlo, Kimpankatuosoite, Kimpanposti

**KIMPPAOSAKKAAT**
Kimppaosakas sekajäte
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Kimppaosakas biojäte
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Kimppaosakas muovipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Kimppaosakas kartonkipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Kimppaosakas lasipakkaus
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

Kimppaosakas metalli
Lähde: Kuljetustiedot ja/tai Salpakierron kimppa-aineisto
Prosessi, josta tieto saadaan: kuljetustiedot ja kimppatiedot kuljetustietomuodossa viedään tietokantaan (kvartaaleittain)
Haltijannimi, Haltijankatuosoite, Haltijanposti (postinumero ja postitoimipaikka)

PÄÄTÖKSET
Päätöksen saaja
Lähde: Päätökset Master
Prosessi, josta tieto saadaan: Päätökset master viedään tietokantaan (tietojen vientisykli tarkentuu myöhemmin)
Lähettäjä/vastaanottaja

KOMPOSTOINTI
Kompostoinnin yhteyshenkilö
Lähde: Kompostointi Master
Prosessi, josta tieto saadaan: Kompostointi master viedään tietokantaan (tietojen vientisykli tarkentuu myöhemmin)
Kompostoinnin vastuuhenkilön yhteystiedot:Etunimi, Kompostoinnin vastuuhenkilön yhteystiedot:Sukunimi, Kompostoinnin vastuuhenkilön yhteystiedot:Puhelinnumero, Kompostoinnin vastuuhenkilön yhteystiedot:Sähköposti, Kompostoinnin 
vastuuhenkilön yhteystiedot:Postiosoite, Kompostoinnin vastuuhenkilön yhteystiedot:Postinumero, Kompostoinnin vastuuhenkilön yhteystiedot:Postitoimipaikka

Kompostorin käyttäjä
Lähde: Kompostointi Master
Prosessi, josta tieto saadaan: Kompostointi master viedään tietokantaan (tietojen vientisykli tarkentuu myöhemmin)
1. Kompostoria käyttävän rakennuksen tiedot:Haltijan etunimi, 1. Kompostoria käyttävän rakennuksen tiedot:Haltijan sukunimi, 1. Kompostoria käyttävän rakennuksen tiedot:Rakennuksen katuosoite, 1. Kompostoria käyttävän rakennuksen tiedot: Rakennuksen postinumero, 1. Kompostoria käyttävän rakennuksen tiedot:Rakennuksen postitoimipaikka

**Comment by ltalve** [comment]
Päätetty 1/2024, että käyttäjän tietoja ei tarvita eikä lueta kantaan.
