### ISSUE TITLE
Erottele kohteiden luonnissa ns. merkitsevät ja ei-merkitsevät rakennukset

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-lahti#74]
Tällä hetkellä kaikkia kiinteistön rakennuksia tarkastellaan samalla tavalla, ja niistä luodaan uusia kohteita saman logiikan mukaisesti.

Tehdään tähän issuen https://github.com/GispoCoding/jkr-lahti/issues/64 edellyttämä muutos: jaetaan rakennukset merkitseviin ja ei-merkitseviin rakennuksiin. Tehtävä erillinen funktio, joka tarkistaa onko rakennus merkitsevä:

- Rakennusluokitus 1994: 011-041, 139, 511-549, 221- 239 + saunat (931)
- Muut rakennukset, joissa huoneisto.

Näiden rakennusten kohteille voidaan aina lisätä tai poistaa muita (ei-merkitseviä) rakennuksia. 

Jos merkitsevä rakennus lakkaa olemasta, omistaja muuttuu, tulee lisää merkitseviä rakennuksia jne., luodaan aina uusi kohde.

**Comment by TiiaY** [comment]
@Rikuoja @LKajan @ltalve Ei tarvitse merkitä näitä, jos kohteet luotu alkuperäisen määrittelyn mukaisesti: https://lahti.sharepoint.com/:w:/r/sites/LahtiJtehuollonjrjestelmprojekti-Materiaalit/Jaetut%20asiakirjat/Materiaalit/Lahden%20m%C3%A4%C3%A4rittelyt/M%C3%84%C3%84RITTELY%20kohteen%20muodostus%20JKRss%C3%A4%207.12.2022.docx?d=w60340f9d5e30432f8d3f5b3b45e27a77&csf=1&web=1&e=eza47d

Määrittelyssä on eritelty rakennukset tyypeittäin, eikä kaikkia rakennuksia kohdella samalla lailla.

**Comment by Rikuoja** [comment]
Tällä hetkellä virhe tulee juuri siitä, että tontin *ylimääräisiä* rakennuksia kohdellaan eri tavalla sen mukaan, milloin itse alkuperäinen kohde muodostetaan. Ja silloin voi käydä niin, että näistä kohteen ulkopuolelle jäävistä ei-merkitsevistä rakennuksista (autotallit) tulee ylimääräisiä virheellisiä kohteita, kuten jo huomasitte kohdeongelmia listatessa.

Tein siitä oman issuen https://github.com/GispoCoding/jkr-core/issues/37 , nämä kaksi on helpointa korjata samalla kertaa, niin ettei näistä ei-merkitsevistä rakennuksista synny koskaan kohteita.

**Comment by Rikuoja** [comment]
Tällä hetkellä on tosiaan katsottu tuota asukasta, ja sen jälkeen ei ole huomattu katsoa enää muiden rakennusten rakennustyyppejä. @TiiaY Onko tuo rakennustyyppilista nyt lopullinen? Kysyin tuolla toisessa issuessa https://github.com/GispoCoding/jkr-lahti/issues/64

> Alempana kuitenkin on erilainen ehto (kohteet joissa 011 tai 041+ luonnollisen henkilön omistamat). Kumpi näistä on merkitsevän rakennuksen määritelmä? Onko tässä kaksi eri määritelmää merkitsevälle rakennukselle eri vaiheissa?

**Comment by Rikuoja** [comment]
@TiiaY Lisäksi vielä yksi kysymys saunoista: tuolla toisessa dokumentissa esiintyi saunoja, jotka oli virheellisesti liitetty kohteelle. Tarkoittaako tämä siis sitä, että samalla kiinteistöllä

a) saunoja ei pitäisi koskaan liittää kohteelle,
b) saunat voi liittää kohteelle, jos niissä ei ole asukasta,
c) saunat pitäisi aina liittää kohteelle vai
d) jotain muuta, vähän muiden rakennusten tyypistä riippuen?

Eli siis yritän ehkä kysyä, onko sauna erikoistapaus (merkitsevä tai ei-merkitsevä) vähän tilanteen mukaan? Vai onko sauna aina oma merkitsevä rakennuksensa, kuten alussa lukee?

**Comment by ltalve** [comment]
Q&A-sessiossa päätetty: Merkitsevät rakennukset ovat joka puolella aina samat.

**Comment by Rikuoja** [comment]
Fixed in https://github.com/GispoCoding/jkr-core/commit/96ae30dede0dad5e1e98b1134e8d8abeb1b64725
