### ISSUE TITLE
Tutki kuljetustietojen skripti päivittyneen kohdennuslogiikan ja kohteiden osalta

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#77]
Kohteissa on tehty paljon muutoksia syksyllä 2022 tehdyn ensimmäisen kuljetustietoimportin jälkeen. Täytyy selvittää mitkä osat koodissa toimivat ja mitä täytyy muuttaa, jotta kuljetustiedot lähtevät kohdentumaan oikein uuden logiikan mukaan luoduille kohteille ja päivitetyn kohdennuslogiikan (28.8.2023, alla) mukaan. Selvityksen perusteella kuljetustietoihin liittyvät seikat päivitetään.

Keskeisimmät liittyvät tarinat:
#57 
#48 

### Kuljetustiedon kohdennus

Kuljetustiedon PRT (sarake F) on sama kuin kohteen yhden rakennuksen PRT.  

Kuljetustiedonurakoitsija urakoitsija (sarake A) ja kohdeosoite (sarake G-H) ja kohde-id (sarake E) ovat samoja kuin aiemmin kohteelle viedyssä kuljetustietoaineistossa. 

Huom! Kuljetustietoa ei verrata kohteen rakennuksien DVV-tietoihin vaan aiempaan kuljetustietoon. 

### Järjestelmään vietävät aineistot:
- 2021 Kuljetustiedot, yksi vuosiaineisto (kaikissa PRT) 
- 2022 Kuljetustiedot, aineisto neljässä kvartaalissa (kaikissa PRT) 
- 2023 Kuljetustiedot, ensimmäinen kvartaali (osassa PRT) 

---

Lahdelta kommentti 16.5.2023: Ennen kuljetustietojen uudelleen viemistä tai scripitin miettimästä tulee olla yhteisesti selvää
- [ ] Mitä sarakkeita kulejtustieto-Exceleistä viedään ja minne JKR tauluihin ja millä otsikolla. -> Gispo toimittaa dokumentin.
- [ ] Mitkä tierdot ovat JKR:n kannalta pakollisia ja miksi. -> Gispo toimittaa dokumentin.

Ks. myös teamsin aineisto, jossa kuljetustietoaineiston tarkka kuvaus: _Kiinteä jäte vietävien kuljetustietojen määrittely 28.8.2023.xlsx_

**Comment by ltalve** [comment]
4.10. palaverissa esitetty kysymys paritaloista ja kuljetustiedoista: 
Paritalot = kaksi kohdetta, joissa molemmissa näkyy sama rakennus, jolla samat osapuolet > tuleeko ongelma kuljetusten kohdennuksessa, ts. löytääkö kuljetus rakennukselta oikean kohteen?

**Comment by ismogis** [comment]
Pakolliset tiedot (muokkaus kesken):

UrakoitsijaID - yksilöi urakoitsijan
UrakoitsijankohdeId - yksilöi urakoitsijan kohteen

Vaihtoehtoiset tiedot kohdentamiseen:
a) Rakennustunnus / Kiinteistotunnus
b) Kiinteistonkatuosoite + Kiinteistonposti

**Comment by ismogis** [comment]
"Huom! Kuljetustietoa ei verrata kohteen rakennuksien DVV-tietoihin vaan aiempaan kuljetustietoon."

Yksinkertaisin ratkaisu tähän saattaa olla luoda kuljetustiedosta tunniste, jota käytetään vertaamiseen.

**Comment by ismogis** [comment]
**Kuljetustieto-excelistä viedään tietokannan tauluihin datat seuraavasti** (kesken)

koko - jkr.keraysvaline:tilavuus

**Comment by ismogis** [comment]
@AnniinaMet @TiiaY Yllä listaus tietokanta-excelistä luettavista kentistä.

**Comment by ltalve** [comment]
Kuljetustietojen osalta tarvittavat toimenpiteet listattu tämän seikan perusteella ja näistä tehdään uudet eritellyt seikat. Tämä seikka suljetaan.

**Comment by AnniinaMet** [comment]
Jätehuollon huomioita Kuljetustieto-excelistä vietävään dataan:

> * Rakennustunnus/Kiinteistotunnus - ei lueta
Tämä pitäisi kyllä lukea sisään, koska sen perusteella tieto kohdentuu. Ei sille ole välttämätöntä paikkaa olla, mutta rakennus id tulee tietoa vietäessä huomioida.

> * Haltijanyhteyshlo - jkr.osapuoli:nimi
Ei ole tarpeen lukea

> * SUM(paino) - jkr.kuljetus:massa
Nykyisen määrittelyn mukaisesti ei ole tarpeen lukea sisään, mutta tuota kyllä saatetaan myöhemmin tarvita lietekuljetustiedoissa, eli on sille hyvä varata nyt jo poikka. Kuljetustietojen muoto on kuitenkin likimain sama

> * kertaaviikossa - ei lueta
Tämä on määritelty luettavaksi ja sille pitäisi löytyä paikka.

> * Voimassaoloviikotalkaen2 - ei lueta
> * Voimassaoloviikotasti2 - ei lueta
> * tyhjennysvali2 - ei lueta
> * kertaaviikossa2 - ei lueta
Näistä kaikki pitäisi lukea sisään ja niille pitäisi löytyä paikka. Kyseessä on tapaukset, joissa asiakkaalla on kaksi eri rytmiä.

> * Keskeytysalkaen - ei lueta
> * Keskeytysasti - ei lueta
Nämä tulee lukea sisään ja nille tulee löytyä paikka

> * KimpanNimi
Kimpan nimi ei ole jätehuollolle olennaista tietoa, eikä sitä jätehuollon määrittelyn mukaan ole tarpeen viedä kantaan. Jos siitä kuitenkin on apua kimpan käsittelyssä tietokannassa, niin toki sen voi viedä. Kimpan yhteyshenkilöntieto, eli "kimpasta vastaava" sen sijaan tulee olla tietokannassa nähtävissä ja sieltä saatavissa.

**Taulu jkr.ulkoinen_asiakastieto**
> * Haltijanyhteyshlo
Ei ole tarpeen viedä tietokantaan

> * KimpanNimi
Kimpan nimi ei ole jätehuollolle olennaista tietoa, eikä sitä jätehuollon määrittelyn mukaan ole tarpeen viedä kantaan. Jos siitä kuitenkin on apua kimpan käsittelyssä tietokannassa, niin toki sen voi viedä. Kimpan yhteyshenkilöntieto, eli "kimpasta vastaava" sen sijaan tulee olla tietokannassa nähtävissä ja sieltä saatavissa.

Jos tässä taulussa on kuljetustietoa, kuten tyhjennysvälit ja käyntimäärät, niin myös seuraaville tiedoille tullee löytyä paikka:
> * Voimassaoloviikotalkaen2
> * Voimassaoloviikotasti2
> * tyhjennysvali2
> * kertaaviikossa2

@ltalve @ismogis

**Comment by ismogis** [comment]
"Rakennustunnus/Kiinteistotunnus - ei lueta
Tämä pitäisi kyllä lukea sisään, koska sen perusteella tieto kohdentuu. Ei sille ole välttämätöntä paikkaa olla, mutta rakennus id tulee tietoa vietäessä huomioida."

Tämän luku lisätty PR:ssä #94.
