### ISSUE TITLE
Muuttuvat kohde id:t

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/jkr-lahti#78]
Joidenkin kohteiden id:t muuttuvat, tutkittava ja korjattava niin ettei kohteiden id:t muutu turhaan.

**Comment by ismogis** [comment]
Tämä liittyy mahdollisesti siihen, että sama kohde saattaa saada eri id:n myös eri luontikerroilla. Todettu viemällä sama data ensin paikalliseen kantaan ja sitten kehityskantaan.  Kohde saa saman sisällön, mutta muodostuu eri vaiheessa ajoa.

**Comment by ismogis** [comment]
Yritin löytää kohdetta, jonka id muuttuisi. Käytössä haara Lahti-64-DVV-tietojen-päivittäminen, kohteet luotu DVV 2022:lla ja perusmaksurekisterin 28.8.23-versiolla, päivitetty DVV 2023:lla. Vertasin kohde-taulun sisältöä järjestettynä geometrian mukaan ja kävin läpi poikkeamia. Kaikki poikkeamat olivat loogisia (uusi rakennus, paritalon kohteet eri järjestyksessä, ...), enkä löytänyt kohdetta, jonka id olisi muuttunut päivityksessä. Ehdottaisin, ettei kannata tutkia enempää, ellei saada kuvattua bugia tarkemmin.
