### ISSUE TITLE
Asukkaista vain voimassaoleva vanhin osapuoleksi

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/jkr-lahti#79]
Luodessa:
Vain dvv:stä löytyvä vanhin asukkaista osapuoleksi, kun kohde luodaan ilman perusmaksurekisteriä.

Päivittäessä:
Tällä hetkellä kun asukas vaihtuu, uuden kohteen osapuoliksi jää myös edellinen vanhin.

**Comment by ismogis** [comment]
Luonti toimii oikein sekä mainissa että haarassa, jossa mukana tietojen päivittäminen. Lisätty myös testi haaraan Lahti-vain-vanhin-asukas-osapuoleksi.

Selvityksessä, mitä tapahtuu päivittäessä.

**Comment by ismogis** [comment]
Kohde.py:n funktiossa get_or_create_kohteet_from_kiinteistot kohdassa "Ladataan vanhimmat asukkaat..." pitäisi tarkistaa, että loppupvm:ää ei ole.

**Comment by ismogis** [comment]
https://github.com/GispoCoding/jkr-core/pull/52
