### ISSUE TITLE
Omistajien ja vanhimpien päivityslogiikan korjaus

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/jkr-lahti#81]
Korjaa logiikka niin että vanhimman muuttaessa uuteen osoitteeseen vanha osapuolitieto ei päivity ( pelkkä hetu ei riitä, vaatii uuden muutoksen tietokantamalliin). Tarkista tarvitaanko sama omistajille, ja korjaa tarpeen mukaan.

**Comment by ltalve** [comment]
Tutkittava vielä mitä osapuolille käy, jos kohteeseen ei tule uutta omistajaa.
