### ISSUE TITLE
Lisää rakennuksille huoneistojen lukumäärä

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#83]
Velvoitetarkistuksia varten tietokantaan tulee lisätä rakennuksille tieto huoneistojen lukumäärästä. Aineistossa käytössä prt.

**Comment by ltalve** [comment]
Nykyinen aineisto on vuodelta 2021. Aineiston päivittäminen toistaiseksi suunnittelematta.

**Comment by ismogis** [comment]
Taulussa jkr.rakennus on huoneistomaara sekä tietomallissa että kannassa. Vientiskripti tai vastaava puuttuu.
