### ISSUE TITLE
Kohteiden luonnin korjaus DVV-päivitysajon jälkeen

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/jkr-lahti#86]
- Kohteiden luonti kaatuu paritalokohteiden luonnin yhteydessä, dvv-päivitys skriptin ajon jälkeen.
- KeyError get_or_create_kohteet_from_vanhimmat.

`Traceback (most recent call last):
  File "C:\Projektit\jkr-core\jkrimporter\providers\db\dbprovider.py", line 331, in write_dvv_kohteet
    import_dvv_kohteet(session, poimintapvm, loppupvm, perusmaksutiedosto)
  File "C:\Projektit\jkr-core\jkrimporter\providers\db\dbprovider.py", line 228, in import_dvv_kohteet
    paritalo_kohteet = get_or_create_paritalo_kohteet(session, poimintapvm, loppupvm)
  File "C:\Projektit\jkr-core\jkrimporter\providers\db\services\kohde.py", line 1274, in get_or_create_paritalo_kohteet
    return get_or_create_kohteet_from_vanhimmat(
  File "C:\Projektit\jkr-core\jkrimporter\providers\db\services\kohde.py", line 892, in get_or_create_kohteet_from_vanhimmat
    {dvv_rakennustiedot[vanhin.rakennus_id]},
KeyError: 66405`

**Comment by ismogis** [comment]
Sain toistettua. Testitapauksista puuttuu paritalokohde ja kohteiden luonnin testaus päivityksen jälkeen. Lisätään ensin paritalokohde dataan, ja tehdään tarvittaessa testaus päivityksen jälkeiselle kohteiden luonnille.

**Comment by ismogis** [comment]
Lisätty testeihin paritalokohde, DVV-päivitys ja kohteiden päivitys. Ongelma ei esiinny näissä testeissä. Tarkistetaan, onko ongelman aiheuttaneeseen kohteeseen tullut muutosta DVV-versioiden välillä vai tuleeko virhe vain silloin, kun kohteet luodaan ensimmäistä kertaa DVV-päivityksen jälkeen.

**Comment by ismogis** [comment]
Ongelman aiheuttaneeseen kohteeseen ei ole tullut muutoksia DVV-versioiden välillä. Ongelma ei myöskään toistu testidatalla, vaikka kohteet loisi ensimmäistä kertaa DVV-päivityksen jälkeen. Tässä vaiheessa epäselvää, miten testitapaus poikkeaa oikeasta datasta.

**Comment by ismogis** [comment]
Testitapaus ei poikkea oikeasta datasta, vaan ongelma liittynee pelkästään siihen, ettei import_dvv_kohteet-funktiolle anneta loppupäivämäärää.

**Comment by ismogis** [comment]
Korjattu kohteen voimassaolon tarkoitus, kun loppupäivämäärää ei anneta, mutta kaatuu oikealla datalla edelleen johonkin paritalokohteeseen (eri kuin aiemmin).
