### ISSUE TITLE
Lisää DVV-päivityksen yhteydessä päättyvien kohteiden loppupäivämääräksi poimintapvm -1

### ISSUE THREAD

**Issue by ltalve** [GispoCoding/jkr-lahti#90]

**Comment by ismogis** [comment]
Testausta vaille valmiina haarassa Lahti-90-lisaa-loppupvm-kohteille-dvv-paivitys. Huomattava, että ei voida viedä suoraan kehityspalvelimelle, sillä poimintapäivämäärän pitää aina olla edellisen poimintapäivämäärän jälkeen. Yksi mahdollisuus on viedä testikannan tilanne, ajaa DVV-päivitys ja tehdä kohteiden päivitys uudelleen.

**Comment by ismogis** [comment]
Testasin omalla koneellani. Molemmat Anniinan mainitsemat kohteet menevät oikein ja näyttää muutenkin hyvältä.
