### ISSUE TITLE
Rakennuksen tiedoista näkyviin vain voimassa olevat vanhimmat ja omistajat

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/jkr-lahti#91]
- Rakennustiedoista asukkaat välilehdellä tulisi näkyä vain voimassaolevat asukkaat.
- Rakennustiedoista omistaja välilehdellä tulisi näkyä vain voimassaolevat omistajat.

- Jätetään rakennus näkyviin myös poistuneille kohteille.

**Comment by ismogis** [comment]
Loppupäivämäärät tallennetaan jo nyt tauluihin rakennuksen_omistajat ja rakennuksen_vanhimmat. Riittää siis muokata QGIS-projektia siten, että näytetään vain voimassaolevat asukkaat ja omistajat.
